import {test} from 'node:test';import assert from 'node:assert/strict';
import {normalizeBook,normalizeKalshi,normalizePoly,suggest,price} from '../lib/arb/adapters.ts';
test('Kalshi YES asks come from NO bids with preserved depth',()=>{const b=normalizeBook('kalshi',{orderbook_fp:{yes_dollars:[['0.6000','3.5']],no_dollars:[['0.7000','7.25']]}});assert.deepEqual(b.yes,[{price:3000,quantity:7.25}]);assert.deepEqual(b.no,[{price:4000,quantity:3.5}]);});
test('US offers and bids are distinct and currencies are enforced',()=>{const x={marketData:{bids:[{px:{value:'0.4000',currency:'USD'},qty:'3'}],offers:[{px:{value:'0.4100',currency:'USD'},qty:'2'}],state:'MARKET_STATE_OPEN'}};const b=normalizeBook('poly',x);assert.equal(b.yes[0].price,4100);assert.equal(b.no[0].price,6000);x.marketData.offers[0].px.currency='EUR';assert.throws(()=>normalizeBook('poly',x));});
test('Precision greater than ten-thousandths is rejected rather than silently rounded',()=>{assert.equal(price('0.0001'),1);assert.throws(()=>price('0.00001'));assert.throws(()=>price('NaN'));});
test('Changing settlement rules invalidates a saved fingerprint',async()=>{const m={slug:'fixture',question:'Will x?',description:'before midnight UTC',marketSides:[],feeCoefficient:.06};const a=await normalizePoly(m),b=await normalizePoly({...m,description:'before midnight ET'});assert.notEqual(a.hash,b.hash);});
test('Unknown Kalshi fee types do not default to general fees',async()=>{const m=await normalizeKalshi({ticker:'ABC-X',status:'active',market_type:'binary',notional_value_dollars:'1.0000'},{fee_type:'new_schedule',fee_multiplier:1});assert.equal(m.feeRate,null);});
test('A multi-year match is excluded from 30-day discovery suggestions',()=>{const base={venue:'kalshi',id:'a',title:'Will Taylor Swift win person of the year?',outcome:'Taylor Swift',closeAt:'2045-01-01T00:00:00Z',open:true};assert.equal(suggest({kalshi:[base],poly:[{...base,id:'b',venue:'poly'}],errors:[],counts:{kalshi:1,poly:1},at:Date.now()}).length,0);});
test('Poly payout comes only from matching published settlement, never last price',async()=>{const m={slug:'fixture',closed:true,status:'MARKET_STATUS_RESOLVED',marketSides:[{long:true,price:'1'}]};assert.equal((await normalizePoly(m)).settlement,null);assert.equal((await normalizePoly(m,{slug:'fixture',settlement:0})).settlement,0);assert.equal((await normalizePoly(m,{slug:'fixture',settlement:.5})).settlement,5000);assert.equal((await normalizePoly(m,{slug:'other',settlement:1})).settlement,null);assert.equal((await normalizePoly({...m,closed:false},{slug:'fixture',settlement:1})).settlement,null);assert.throws(()=>price('1.1'));});

test('Missing or invalid PM-US minimum quantity never defaults to one contract',async()=>{
 for(const minimumTradeQty of [undefined,null,0,-1,NaN,true,'1'])assert.equal((await normalizePoly({slug:'fixture',minimumTradeQty})).minQty,0);
 assert.equal((await normalizePoly({slug:'fixture',minimumTradeQty:0.01})).minQty,0.01);
});
