import test from 'node:test';
import assert from 'node:assert/strict';
import {pair,book} from './research-fixture.ts';
import {candidateWatchPolicy,watchUniverse,scheduleShards,rankWatchQuotes,noiseResilience,routeEconomics,RouteCoverage} from '../lib/pilot/candidate-watch.ts';
import {routeDimensions} from '../lib/research/family-settlement.ts';
import {quoteBounded} from '../lib/pilot/bounded-basis.ts';
function fixture(){const p=pair(),now=Date.now(),source={url:'https://example.test',sha256:'a'.repeat(64)};
 const e={pair:p,family:{id:'f',documents:['K','P'],missingEvidence:[],ordinaryConflicts:[],divergences:[{id:'venue-finality',evidence:'Different exceptional finality'}],stateProofs:[]},proof:{dimensions:Object.fromEntries(routeDimensions.map(k=>[k,{kalshi:k,poly:k,evidence:'Pinned ordinary evidence'}])),missingEvidence:[],conflicts:[]}};
 const fees={kalshi:{marketId:p.a.id,marketHash:p.a.hash,checkedAt:now,expiresAt:now+60000,source,rate:700,model:'KALSHI_FRAGMENT_BOUND',balancePrecisionMicros:100,minFillHundredths:1},poly:{marketId:p.b.id,marketHash:p.b.hash,checkedAt:now,expiresAt:now+60000,source,rate:695,model:'PM_CUMULATIVE'}};
 const books={kalshi:book('kalshi',p.a.id),poly:book('poly',p.b.id)};return {p,e,fees,books,now};}
test('watch accepts bounded ordinary proof with zero account permission input and never authorizes orders',()=>{const f=fixture();assert.equal(watchUniverse([f.e as any]).length,1);assert.equal(candidateWatchPolicy.ordersEnabled,false);assert.equal(candidateWatchPolicy.liveSubmission,'LIVE_SUBMISSION_BLOCKED');assert.equal(candidateWatchPolicy.durationMs,7200000);assert.equal(candidateWatchPolicy.admissionCushion,0);});
test('ordinary conflicts and absent proof remain excluded; residual mismatches remain intact',()=>{const f=fixture();const bad=structuredClone(f.e);bad.pair.id+='bad';bad.proof.conflicts.push('Different ordinary payout');assert.deepEqual(watchUniverse([f.e as any,bad as any]),[f.e]);delete (f.e.proof.dimensions as any).window;assert.equal(watchUniverse([f.e as any]).length,0);assert.equal(f.e.family.divergences.length,1);});
test('entire universe is scheduled once within proven 60-route concurrent limit with both categories',()=>{const f=fixture();const entries=Array.from({length:2852},(_,i)=>({...structuredClone(f.e),pair:{...f.p,id:String(i),a:{...f.p.a,identity:{sports:i%3!==0},closeAt:new Date(f.now+i*10000).toISOString()}}}));const shards=scheduleShards(entries as any,f.now);assert.equal(shards.length,48);assert.ok(shards.every(s=>s.length<=60));assert.equal(new Set(shards.flat().map(x=>x.pair.id)).size,2852);assert.ok(shards[0].some(x=>x.pair.a.identity?.sports));assert.ok(shards[0].some(x=>!x.pair.a.identity?.sports));});
test('route-hours exclude acquisition, gaps, and unobserved blocked event-loop intervals',()=>{const c=new RouteCoverage();c.sample(['a','b'],0);c.sample(['a','b'],250);c.sample([],500);c.sample(['a'],5000);c.sample(['a'],5250);assert.equal(c.summary().monitorableRoutes,2);assert.equal(c.summary().usableRouteHours,750/3600000);c.sample(['a'],10000);assert.equal(c.rows.get('a')!.usableMs,1500);});
test('raw positive spread erased by conservative unknown-account fees is distinguished from no depth',()=>{const f=fixture();f.fees.kalshi.balancePrecisionMicros=10000;f.books.kalshi.yes=[{price:4000,quantity:10}];f.books.poly.no=[{price:4000,quantity:10}];const r=routeEconomics(f.p as any,f.books as any,'yes',f.fees as any,f.now+3600000,f.now);assert.equal(r.rawPositive,true);assert.equal(r.diagnosis,'FEES_OR_COMMITMENT_ERASE_SPREAD');assert.ok(r.quotes.every(q=>q.feeNetProfit<=0));f.books.poly.no=[];assert.equal(routeEconomics(f.p as any,f.books as any,'yes',f.fees as any,f.now+3600000,f.now).diagnosis,'INSUFFICIENT_DEPTH');});
test('positive sub-cushion economics stay counted even when native-tick noise prevents selection',()=>{const f=fixture();f.books.kalshi.yes=[{price:4700,quantity:1}];f.books.poly.no=[{price:4800,quantity:1}];const q=quoteBounded(f.p as any,f.books as any,'yes',f.fees as any,f.now+3600000,f.now,1)[0];assert.ok(q.feeNetProfit>0&&q.feeNetProfit<200);assert.equal(noiseResilience(q,f.fees as any,{kalshi:100,poly:100}).worthwhile,false);assert.equal(noiseResilience(q,f.fees as any,{kalshi:0,poly:100}).reason,'NATIVE_PRICE_GRID_UNPROVEN');});
test('ranking uses net dollars, return, lockup, then depth',()=>{const f=fixture(),q=quoteBounded(f.p as any,f.books as any,'yes',f.fees as any,f.now+3600000,f.now)[0];const rows=[{quote:{...q,pairId:'shallow'},depth:1},{quote:{...q,pairId:'deep'},depth:10},{quote:{...q,pairId:'profit',feeNetProfit:q.feeNetProfit+1},depth:1}];assert.deepEqual(rows.sort(rankWatchQuotes).map(r=>r.quote.pairId),['profit','deep','shallow']);});
