import {test} from 'node:test';import assert from 'node:assert/strict';
import {classifyKalshiCash} from '../lib/pilot/kalshi-cash.ts';import {assessKalshiFunding} from '../lib/pilot/kalshi-funding.ts';import {auditCashConservation} from '../lib/pilot/cash-conservation.ts';import {normalizeCashObservation} from '../lib/pilot/cash-observation.ts';
const base=Date.parse('2026-09-14T12:00:00Z'),iso=(n:number)=>new Date(base+n).toISOString();
const cash=(amount:string,start:number)=>normalizeCashObservation('kalshi',{balance_dollars:amount},{startedAt:base+start,finishedAt:base+start+10,elapsedMs:10},'a'.repeat(64));
const fill=()=>({fill_id:'f',order_id:'user',ticker:'K',market_ticker:'K',side:'yes',outcome_side:'yes',action:'buy',book_side:'bid',exchange_index:0,subaccount_number:0,count_fp:'1',yes_price_dollars:'0.4',no_price_dollars:'0.6',fee_cost:'0.01',created_time:iso(100)});
const record=()=>({ticker:'K',exchange_index:0,revenue:100,settled_time:iso(200)});
const input=()=>({fills:[fill()],settlements:[record()],funding:assessKalshiFunding([],[],base+500),subaccountTransfers:[],intraAccountTransfers:[]});
test('Kalshi unrelated fills and settlement reconcile cash without creating bot profit',()=>{const r=auditCashConservation(cash('100',0),cash('100.59',1000),classifyKalshiCash(input()));assert.equal(r.status,'CONSISTENT_WITH_CLASSIFIED_CASH');assert.equal(r.unrelatedTradeCashFlowMicros,-410000);assert.equal(r.unrelatedSettlementMicros,1000000);assert.equal(r.realizedProfitMicros,null);assert.equal(r.creditAuthorized,false);});
test('Owned settlement cannot be silently treated as unrelated without validated expectation',()=>{const r=classifyKalshiCash(input(),{user:{orderId:'user',marketId:'K',side:'yes',action:'buy'}});assert.equal(r.complete,false);assert.ok(r.unresolved.includes('OWNED_SETTLEMENT_EVIDENCE_REQUIRED'));});
test('Prior observed funding narrows the interval only when unchanged; new unscoped funding cannot prove primary cash',()=>{const d={id:'d',status:'applied',amount_cents:10000,fee_cents:0,created_ts:Math.floor((base-10000)/1000)};const i=input();i.funding=assessKalshiFunding([d],[],base+500);const before=assessKalshiFunding([d],[],base-100);const r=auditCashConservation(cash('100',0),cash('100.59',1000),classifyKalshiCash({...i,priorFunding:before}));assert.equal(r.status,'CONSISTENT_WITH_CLASSIFIED_CASH');assert.equal(auditCashConservation(cash('100',0),cash('100.59',1000),classifyKalshiCash(i)).status,'UNRECONCILED');i.funding=assessKalshiFunding([{...d,amount_cents:20000}],[],base+500);assert.equal(classifyKalshiCash({...i,priorFunding:before}).complete,false);});
test('Transfers, wrong exchange scope, conflicting duplicates and absent time cannot vanish from coverage',()=>{for(const mode of ['transfer','scope','duplicate','time']){const i=input();if(mode==='transfer')(i.subaccountTransfers as unknown[]).push({});if(mode==='scope')i.fills[0].exchange_index=1;if(mode==='duplicate')i.fills.push({...i.fills[0],fee_cost:'0.02'});if(mode==='time')i.fills[0].created_time='';assert.equal(classifyKalshiCash(i).complete,false);}});
test('Cross-venue classified history cannot be applied to a Kalshi balance',()=>{const h=classifyKalshiCash(input());assert.throws(()=>auditCashConservation(cash('100',0),cash('100',1000),{...h,venue:'poly'}));});

import {PilotExecutionLedger} from '../lib/pilot/execution-ledger.ts';import {mkdtempSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';
test('Durable Kalshi audit replays across restart without turning personal settlement into bot profit',()=>{const path=join(mkdtempSync(join(tmpdir(),'kalshi-cash-')),'p.sqlite');let e=new PilotExecutionLedger(path,'synthetic');try{const empty={deposits:[],withdrawals:[],subaccountTransfers:[],intraAccountTransfers:[]};e.recordKalshiFundingObservation('f-before',empty,base-100,'a'.repeat(64));e.recordKalshiFundingObservation('f-after',empty,base+500,'a'.repeat(64));for(const [id,amount,start] of [['before','100',0],['after','100.59',1000]] as const)e.recordCashObservation(id,'kalshi',{balance_dollars:amount},cash(amount,start),'a'.repeat(64));const r=e.recordKalshiCashAudit('audit','before','after','f-before','f-after',[fill()],[record()]);assert.equal(r.status,'CONSISTENT_WITH_CLASSIFIED_CASH');assert.equal(r.expectedSettlementMicros,0);assert.equal(r.unrelatedSettlementMicros,1000000);assert.equal(r.creditAuthorized,false);e.close();e=new PilotExecutionLedger(path,'synthetic');assert.deepEqual(e.recordKalshiCashAudit('audit','before','after','f-before','f-after',[fill()],[record()]),r);assert.throws(()=>e.recordKalshiCashAudit('bad','before','after','f-before','f-before',[fill()],[record()]),/Fresh/);}finally{e.close();}});
