import {test} from 'node:test';import assert from 'node:assert/strict';
import {assessKalshiFunding} from '../lib/pilot/kalshi-funding.ts';
const deposit=()=>({id:'d',status:'applied',amount_cents:1000,fee_cents:0,created_ts:100});
test('Applied deposit without finalization retains a conservative observation bound, never a made-up event time',()=>{const r=assessKalshiFunding([deposit()],[],200000);assert.equal(r.records[0].expectedDepositMicros,10000000);assert.equal(r.records[0].earliestAppliedAt,100000);assert.equal(r.records[0].latestAppliedAt,200000);assert.equal(r.records[0].timeBasis,'OBSERVED_APPLIED_BOUND');assert.equal(r.subaccountAttributionVerified,false);assert.equal(r.creditAuthorized,false);});
test('Final timestamp narrows the interval and duplicate deposits do not add money twice',()=>{const d={...deposit(),finalized_ts:150};const r=assessKalshiFunding([d,{...d}],[],200000);assert.equal(r.records.length,1);assert.equal(r.records[0].latestAppliedAt,150000);assert.equal(r.records[0].timeBasis,'FINALIZED_TIMESTAMP');assert.equal(assessKalshiFunding([d,{...d,amount_cents:2000}],[],200000).complete,false);});
test('Pending, fees, unknown withdrawals and invalid timestamps cannot disappear from cash history',()=>{for(const d of [{...deposit(),status:'pending'},{...deposit(),fee_cents:1},{...deposit(),created_ts:201},{...deposit(),finalized_ts:null},{...deposit(),finalized_ts:99}])assert.equal(assessKalshiFunding([d],[],200000).complete,false);assert.equal(assessKalshiFunding([], [{}],200000).complete,false);});

import {PilotExecutionLedger} from '../lib/pilot/execution-ledger.ts';import {mkdtempSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';
const history=()=>({deposits:[deposit()],withdrawals:[],subaccountTransfers:[],intraAccountTransfers:[]});
test('First funding observation survives restart and establishes prior knowledge without inventing deposit timing',()=>{const path=join(mkdtempSync(join(tmpdir(),'funding-observed-')),'p.sqlite');let e=new PilotExecutionLedger(path,'synthetic');try{e.recordKalshiFundingObservation('first',history(),200000,'a'.repeat(64));e.recordCashObservation('cash','kalshi',{balance_dollars:'100'},{startedAt:201000,finishedAt:201010,elapsedMs:10},'a'.repeat(64));e.close();e=new PilotExecutionLedger(path,'synthetic');const r=e.fundingKnownBeforeCash('first','cash');assert.deepEqual(r.knownAppliedDepositIds,['d']);assert.equal(r.knownAppliedBy,200000);assert.equal(r.creditAuthorized,false);e.recordKalshiFundingObservation('later',history(),202000,'a'.repeat(64));assert.throws(()=>e.fundingKnownBeforeCash('later','cash'),/before/);assert.equal(e.fundingKnownBeforeCash('first','cash').knownAppliedBy,200000);assert.throws(()=>e.recordKalshiFundingObservation('first',history(),202000,'a'.repeat(64)),/conflict/);}finally{e.close();}});
test('Pending deposits, any transfers and credential changes prevent prior-funding exclusion',()=>{const e=new PilotExecutionLedger(':memory:','synthetic');try{e.recordCashObservation('cash','kalshi',{balance_dollars:'100'},{startedAt:201000,finishedAt:201010,elapsedMs:10},'a'.repeat(64));for(const kind of ['pending','transfer','credential']){const h=history();if(kind==='pending')h.deposits[0].status='pending';if(kind==='transfer')(h.subaccountTransfers as unknown[]).push({});e.recordKalshiFundingObservation(kind,h,200000,(kind==='credential'?'b':'a').repeat(64));assert.throws(()=>e.fundingKnownBeforeCash(kind,'cash'));}}finally{e.close();}});
