import {test} from 'node:test';import assert from 'node:assert/strict';
import {initial,settle} from '../lib/arb/ledger.ts';import {planExit,applyExitLeg} from '../lib/arb/paper-exit.ts';import {pair,book} from './research-fixture.ts';import type {State} from '../lib/arb/types.ts';
function setup(){const now=Date.now(),s=initial();s.positions=[{id:'exit',pair:{...pair(),reviewed:true},quote:{quantity:2,aSide:'yes',bSide:'no'} as any,aQuantity:2,bQuantity:2,aDebit:6000,bDebit:6000,status:'open',openedAt:now}] as any;s.cash={kalshi:494000,poly:494000};const books={a:{...book('kalshi','K',0,now),yesBids:[{price:6000,quantity:2}]},b:{...book('poly','P',0,now),noBids:[{price:6000,quantity:2}]}};return {s,now,books};}
test('Exit uses bids after fees, requires full depth and rejects stale/future books',()=>{const {s,now,books}=setup();assert.ok(planExit(s,'exit',books,now));for(const a of [{...books.a,yesBids:[{price:6000,quantity:1}]},{...books.a,receivedAt:now-3000},{...books.a,receivedAt:now+1},{...books.a,exchangeAt:now+1}])assert.equal(planExit(s,'exit',{...books,a},now),null);assert.equal(planExit(s,'exit',{a:{...books.a,yesBids:[{price:3000,quantity:2}]},b:{...books.b,noBids:[{price:3000,quantity:2}]}},now),null);});
test('Exit delay, leg persistence, failed second leg and eventual settlement conserve cash',()=>{const {s,now,books}=setup(),plan=planExit(s,'exit',books,now)!;assert.throws(()=>applyExitLeg(s,plan,'a',books.a,now+499));const a={...books.a,receivedAt:now+500,exchangeAt:now+500},one=applyExitLeg(s,plan,'a',a,now+500);assert.equal(one.positions[0].status,'unmatched');assert.equal(s.positions[0].aPayout,undefined);assert.throws(()=>applyExitLeg(one,plan,'a',a,now+501));const bad={...books.b,noBids:[{price:1000,quantity:2}],receivedAt:now+1000,exchangeAt:now+1000};assert.equal(applyExitLeg(one,plan,'b',bad,now+1000),one);const done=settle(one,'exit',10000,0,now+2000);assert.equal(done.cash.kalshi,one.cash.kalshi);assert.equal(done.cash.poly,one.cash.poly+20000);assert.equal(done.positions[0].profit,done.positions[0].aPayout!+20000-12000);});
test('Two delayed exit legs close once and retain execution evidence',()=>{const {s,now,books}=setup(),plan=planExit(s,'exit',books,now)!;let next:State=s;for(const key of ['a','b'] as const)next=applyExitLeg(next,plan,key,{...books[key],receivedAt:now+1000,exchangeAt:now+1000},now+1000);const p=next.positions[0];assert.equal(p.closedBy,'early-exit');assert.equal(p.paperExits?.length,2);assert.equal(p.profit,plan.profit);assert.equal(next.cash.kalshi+next.cash.poly,1000000+plan.profit);assert.equal(settle(next,'exit',10000,0),next);});
test('Unhedged recovery sells only held contracts and does not invent the absent leg',()=>{const {s,now,books}=setup(),p=s.positions[0];p.bQuantity=0;p.bPayout=0;p.bDebit=0;s.cash.poly=500000;const plan=planExit(s,'exit',{a:books.a},now)!;assert.equal(plan.legs.length,1);const next=applyExitLeg(s,plan,'a',{...books.a,receivedAt:now+500,exchangeAt:now+500},now+500);assert.equal(next.positions[0].status,'settled');assert.equal(next.cash.poly,500000);assert.equal(next.positions[0].profit,plan.profit);});
test('Failed hedge recovery accepts a recorded loss, while matched positions retain profit gate',()=>{
 const {s,now,books}=setup(),p=s.positions[0];p.status='unmatched';p.bQuantity=0;p.bPayout=0;p.bDebit=0;s.cash.poly=500000;
 const low={...books.a,yesBids:[{price:1000,quantity:2}]};const plan=planExit(s,'exit',{a:low},now);assert.ok(plan);assert.ok(plan.profit<0);
 const next=applyExitLeg(s,plan,'a',{...low,receivedAt:now+500,exchangeAt:now+500},now+500);assert.equal(next.positions[0].profit,plan.profit);assert.ok(next.cash.kalshi>s.cash.kalshi);assert.equal(next.positions[0].status,'settled');assert.equal(next.positions[0].paperExits?.[0].reason,'unhedged-recovery');
 const paired=setup();assert.equal(planExit(paired.s,'exit',{a:low,b:{...books.b,noBids:[{price:1000,quantity:2}]}},now),null);
 const worthless={...low,yesBids:[{price:100,quantity:2}]};assert.equal(planExit(s,'exit',{a:worthless},now),null,'do not sell when costs consume all proceeds');
});
