import {test} from 'node:test';import assert from 'node:assert/strict';
import {normalizeCashObservation} from '../lib/pilot/cash-observation.ts';
import {classifyPolyCashActivities,auditCashConservation} from '../lib/pilot/cash-conservation.ts';
const base=Date.parse('2026-09-14T12:00:00Z'),iso=(n:number)=>new Date(base+n).toISOString();
const obs=(cash:string,start:number)=>normalizeCashObservation('poly',{balances:[{currency:'USD',currentBalance:cash,buyingPower:cash}]},{startedAt:base+start,finishedAt:base+start+10,elapsedMs:10},'a'.repeat(64));
function deposit(){return {type:'ACTIVITY_TYPE_ACCOUNT_DEPOSIT',accountBalanceChange:{status:'ACCOUNT_BALANCE_CHANGE_STATUS_COMPLETED',transactionId:'d',amount:{value:'10',currency:'USD'},createTime:iso(100),updateTime:iso(150)}};}
function trade(){return {type:'ACTIVITY_TYPE_TRADE',trade:{marketSlug:'P',isAggressor:true,createTime:iso(200),updateTime:iso(210),aggressorExecution:{id:'f',type:'EXECUTION_TYPE_FILL',aggressor:true,order:{id:'bot',marketSlug:'P',intent:'ORDER_INTENT_BUY_LONG',outcomeSide:'OUTCOME_SIDE_YES',action:'ORDER_ACTION_BUY'},lastShares:'1',lastPx:{value:'0.4',currency:'USD'},commissionNotionalCollected:{value:'0.000001',currency:'USD'}}}};}
test('Deposits explain cash but never profit, and exact trade fees stay separate',()=>{const h=classifyPolyCashActivities([deposit(),trade()],{bot:{orderId:'bot',marketId:'P',side:'yes',action:'buy'}});const r=auditCashConservation(obs('100',0),obs('109.599999',1000),h);assert.equal(r.status,'CONSISTENT_WITH_CLASSIFIED_CASH');assert.equal(r.externalDepositMicros,10000000);assert.equal(r.ownedTradeCashFlowMicros,-400001);assert.equal(r.realizedProfitMicros,null);assert.equal(r.creditAuthorized,false);});
test('Unrelated trades remain external to bot attribution',()=>{const h=classifyPolyCashActivities([trade()]);const r=auditCashConservation(obs('100',0),obs('99.599999',1000),h);assert.equal(r.unrelatedTradeCashFlowMicros,-400001);assert.equal(r.ownedTradeCashFlowMicros,0);});
test('Unknown settlements, withdrawals, rebates and pending deposits block even a coincidentally matching balance',()=>{for(const type of ['ACTIVITY_TYPE_POSITION_RESOLUTION','ACTIVITY_TYPE_ACCOUNT_WITHDRAWAL','ACTIVITY_TYPE_TAKER_FEE_REBATE']){const h=classifyPolyCashActivities([{type}]);assert.equal(auditCashConservation(obs('100',0),obs('100',1000),h).status,'UNRECONCILED');}const d=deposit();d.accountBalanceChange.status='ACCOUNT_BALANCE_CHANGE_STATUS_PENDING';assert.equal(classifyPolyCashActivities([d]).complete,false);});
test('Duplicate events cannot add money twice and conflicting amounts block conservation',()=>{const d=deposit();const h=classifyPolyCashActivities([d,structuredClone(d)]);assert.equal(h.movements.length,1);assert.equal(auditCashConservation(obs('100',0),obs('110',1000),h).status,'CONSISTENT_WITH_CLASSIFIED_CASH');const conflict=structuredClone(d);conflict.accountBalanceChange.amount.value='20';assert.equal(classifyPolyCashActivities([d,conflict]).complete,false);});
test('Unexplained balance changes and overlapping observation intervals are never settlement proof',()=>{assert.equal(auditCashConservation(obs('100',0),obs('101',1000),classifyPolyCashActivities([])).unexplainedDeltaMicros,1000000);const d=deposit();d.accountBalanceChange.createTime=iso(5);const r=auditCashConservation(obs('100',0),obs('110',1000),classifyPolyCashActivities([d]));assert.ok(r.reasons.includes('CASH_EVENT_OVERLAPS_OBSERVATION'));assert.throws(()=>auditCashConservation(obs('100',0),obs('100',5),classifyPolyCashActivities([])));});
test('Credential changes, malformed trade ownership and absent timestamps fail closed',()=>{const after=obs('100',1000);after.credentialScope='b'.repeat(64);assert.throws(()=>auditCashConservation(obs('100',0),after,classifyPolyCashActivities([])));const t=trade();t.trade.aggressorExecution.aggressor=false;assert.equal(classifyPolyCashActivities([t]).complete,false);const d=deposit();d.accountBalanceChange.updateTime='';assert.equal(classifyPolyCashActivities([d]).complete,false);});

import {PilotExecutionLedger} from '../lib/pilot/execution-ledger.ts';import {mkdtempSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';
test('Durable audit survives restart, deduplicates replay and halts unexplained cash without crediting it',()=>{const path=join(mkdtempSync(join(tmpdir(),'cash-audit-')),'p.sqlite');let e=new PilotExecutionLedger(path,'synthetic');try{for(const [id,cash,start] of [['before','100',0],['after','110',1000]] as const){const o=obs(cash,start);e.recordCashObservation(id,'poly',{balances:[{currency:'USD',currentBalance:cash,buyingPower:cash}]},o,o.credentialScope);}const first=e.recordPolyCashAudit('audit','before','after',[deposit()]);assert.equal(first.status,'CONSISTENT_WITH_CLASSIFIED_CASH');e.close();e=new PilotExecutionLedger(path,'synthetic');assert.deepEqual(e.recordPolyCashAudit('audit','before','after',[deposit()]),first);assert.throws(()=>e.recordPolyCashAudit('audit','before','after',[]),/conflict/);const failed=e.recordPolyCashAudit('unexplained','before','after',[]);assert.equal(failed.status,'UNRECONCILED');assert.equal(failed.creditAuthorized,false);e.close();e=new PilotExecutionLedger(path,'synthetic');assert.equal((e.ledger.db.prepare('select halted from pilot_control').get() as any).halted,1);assert.equal((e.ledger.db.prepare('select count(*) n from pilot_cash_audits').get() as any).n,2);}finally{e.close();}});

test('Cash audit persistence failure retains rejected evidence and a halt without recording a successful audit',()=>{const e=new PilotExecutionLedger(':memory:','synthetic');try{for(const [id,cash,start] of [['before','100',0],['after','110',1000]] as const){const o=obs(cash,start);e.recordCashObservation(id,'poly',{balances:[{currency:'USD',currentBalance:cash,buyingPower:cash}]},o,o.credentialScope);}e.ledger.db.exec("CREATE TRIGGER fail_audit BEFORE INSERT ON pilot_cash_audits BEGIN SELECT RAISE(ABORT,'injected cash audit persistence failure'); END");assert.throws(()=>e.recordPolyCashAudit('audit','before','after',[deposit()]),/injected/);assert.equal((e.ledger.db.prepare('select count(*) n from pilot_cash_audits').get() as any).n,0);const failed=e.ledger.db.prepare('select input,error from pilot_cash_failures').get() as any;assert.equal(JSON.parse(failed.input).activities.length,1);assert.equal((e.ledger.db.prepare('select halted from pilot_control').get() as any).halted,1);}finally{e.close();}});
