import {test} from 'node:test';import assert from 'node:assert/strict';
import {assessPolySettlement} from '../lib/pilot/settlement-evidence.ts';
const usd=(value:string)=>({value,currency:'USD'});
function fixture(side:'yes'|'no'='yes',settlement=1){
 const order={id:'bot',marketSlug:'P',intent:side==='yes'?'ORDER_INTENT_BUY_LONG':'ORDER_INTENT_BUY_SHORT',outcomeSide:side==='yes'?'OUTCOME_SIDE_YES':'OUTCOME_SIDE_NO',action:'ORDER_ACTION_BUY'};
 const execution={id:'f',type:'EXECUTION_TYPE_FILL',aggressor:true,order,lastShares:'1',lastPx:usd(side==='yes'?'0.4':'0.6'),commissionNotionalCollected:usd('0.000001')};
 const before={netPositionDecimal:side==='yes'?'1':'-1',qtyBoughtDecimal:'1',qtySoldDecimal:'0',cost:usd('0.4'),realized:usd('0'),cashValue:usd('1'),baseCost:null,fees:null};
 return {expected:{orderId:'bot',marketId:'P',side,action:'buy' as const},ownedFillIds:['f'],accountActivities:[{type:'ACTIVITY_TYPE_TRADE',trade:{marketSlug:'P',isAggressor:true,aggressorExecution:execution}}],record:{type:'ACTIVITY_TYPE_POSITION_RESOLUTION',positionResolution:{marketSlug:'P',side:side==='yes'?'POSITION_RESOLUTION_SIDE_LONG':'POSITION_RESOLUTION_SIDE_SHORT',market:{slug:'P',status:'MARKET_STATUS_RESOLVED',closed:true},updateTime:'2026-09-14T20:00:00Z',tradeId:'',beforePosition:before,afterPosition:{...before,qtySoldDecimal:'1',netPositionDecimal:'0',cashValue:usd('0')}}},published:{slug:'P',settlement}};
}
test('Winning resolution yields expected payout with exact fee, never observed credit or realized account profit',()=>{const r=assessPolySettlement(fixture());assert.equal(r.expectedPayoutMicros,1000000);assert.equal(r.expectedNetCashFlowMicros,599999);assert.equal(r.observedCashCreditMicros,null);assert.equal(r.creditAuthorized,false);});
test('YES and NO ordinary outcomes retain both winning and losing expectations',()=>{for(const side of ['yes','no'] as const)for(const outcome of [0,1]){const r=assessPolySettlement(fixture(side,outcome));assert.equal(r.expectedPayoutMicros,(side==='yes'?outcome:1-outcome)*1000000);assert.equal(r.entryDebitMicros,400001);}});
test('Null cost cannot become zero but unavailable optional fees/baseCost never override exact entry fills',()=>{const x=fixture();assert.equal(assessPolySettlement(x).feeMicros,1);(x.record.positionResolution.beforePosition as any).cost=null;assert.throws(()=>assessPolySettlement(x));});
test('Wrong quantity, nonzero residual, prior sale, cost mismatch and wrong direction fail closed',()=>{for(const mode of ['quantity','residual','sale','resolution-sale','cost','direction']){const x=fixture(),r=x.record.positionResolution;if(mode==='quantity')r.beforePosition.netPositionDecimal='2';if(mode==='residual')r.afterPosition.netPositionDecimal='1';if(mode==='sale')r.beforePosition.qtySoldDecimal='1';if(mode==='resolution-sale')r.afterPosition.qtySoldDecimal='0';if(mode==='cost')r.beforePosition.cost=usd('0.3');if(mode==='direction')r.side='POSITION_RESOLUTION_SIDE_SHORT';assert.throws(()=>assessPolySettlement(x));}});
test('Unresolved, scalar, wrong slug and missing owned or foreign fills cannot establish expected payout',()=>{for(const mode of ['pending','scalar','slug','missing','foreign']){const x=fixture();if(mode==='pending')x.record.positionResolution.market.status='MARKET_STATUS_OPEN';if(mode==='scalar')x.published.settlement=.5;if(mode==='slug')x.published.slug='Q';if(mode==='missing')x.accountActivities=[];if(mode==='foreign')x.accountActivities[0].trade.aggressorExecution.order.id='user';assert.throws(()=>assessPolySettlement(x));}});
test('Duplicate and conflicting fills are handled consistently with the execution ledger',()=>{const x=fixture();x.accountActivities.push(structuredClone(x.accountActivities[0]));assert.equal(assessPolySettlement(x).quantityUnits,10000);x.accountActivities[1].trade.aggressorExecution.commissionNotionalCollected=usd('0.02');assert.throws(()=>assessPolySettlement(x));});
