import {test} from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {PilotExecutionLedger} from '../lib/pilot/execution-ledger.ts';import {pilotPreflight} from '../lib/pilot/preflight.ts';import {pair,book} from './research-fixture.ts';
const now=1789408000000;
function plan(){const p={...pair(),reviewed:true};return pilotPreflight({mapping:{id:p.id,pair:p,status:'MANUAL_VERIFIED',active:true,lastVerifiedAt:now,metadataAt:now} as any,a:book('kalshi','Kp',100,now),b:book('poly','Pp',100,now),aSide:'yes',wall:now,mono:100,health:{streamHealthy:true,persistenceHealthy:true,eventLoopHealthy:true,executionProtocolValidated:true,feesValidated:true},accounts:Object.fromEntries(['kalshi','poly'].map(venue=>[venue,{venue,available:1000000,cumulativeSpent:0,reserved:0,reconciledAt:now,unresolvedOrders:0,unmatchedContracts:0,occupiedMarkets:[]}])) as any});}
function fixture(){const path=join(mkdtempSync(join(tmpdir(),'pilot-execution-')),'pilot.sqlite');let e=new PilotExecutionLedger(path,'synthetic');e.preparePair('pair',plan(),now);for(const venue of ['kalshi','poly'] as const){e.beginSubmission('pair:'+venue,now);e.bindSubmissionResponse('pair:'+venue,venue+'-order');}return {path,get e(){return e;},restart(){e.close();e=new PilotExecutionLedger(path,'synthetic');},close(){e.close();}};}
function poly(q=.5,state='ORDER_STATE_CANCELED',time='2026-09-14T18:00:00Z',fee='0.000001'){
 const order={id:'poly-order',marketSlug:'Pp',intent:'ORDER_INTENT_BUY_SHORT',outcomeSide:'OUTCOME_SIDE_NO',action:'ORDER_ACTION_BUY',quantity:1,cumQuantity:q,leavesQuantity:state==='ORDER_STATE_NEW'?1:state==='ORDER_STATE_PARTIALLY_FILLED'?1-q:0,state,commissionNotionalTotalCollected:{value:q?fee:'0',currency:'USD'},lastTransactTime:time};
 const fills=q?[{id:'p-fill',type:q===1?'EXECUTION_TYPE_FILL':'EXECUTION_TYPE_PARTIAL_FILL',order,lastShares:String(q),lastPx:{value:'0.60',currency:'USD'},commissionNotionalCollected:{value:fee,currency:'USD'}}]:[];return {order,fills};
}
function kalshi(){const fill={fill_id:'k-fill',order_id:'kalshi-order',ticker:'Kp',market_ticker:'Kp',side:'yes',outcome_side:'yes',action:'buy',book_side:'bid',exchange_index:0,subaccount_number:0,count_fp:'1',yes_price_dollars:'0.4',no_price_dollars:'0.6',fee_cost:'0.01'};return {order:{...fill,status:'executed',initial_count_fp:'1',fill_count_fp:'1',remaining_count_fp:'0',taker_fees_dollars:'0.01',maker_fees_dollars:'0',taker_fill_cost_dollars:'0.4',maker_fill_cost_dollars:'0',last_update_time:'2026-09-14T18:00:00Z'},fills:[fill]};}
test('Exact fee and partial inventory survive restart; duplicate and stale evidence never add spend',()=>{
 const x=fixture();try{const k=kalshi(),p=poly();x.e.reconcile('pair:kalshi',k.order,k.fills);x.restart();x.e.reconcile('pair:poly',p.order,p.fills);let r=x.e.pair('pair');assert.equal(r.status,'UNMATCHED');assert.equal(r.cashFlowMicros,-610001);assert.equal(r.legs[1].reservationDebit,2001);assert.equal(r.realizedProfitMicros,null);x.restart();assert.equal(x.e.reconcile('pair:poly',p.order,p.fills).reason,'DUPLICATE');const stale=poly(0,'ORDER_STATE_NEW','2026-09-14T17:59:00Z');assert.equal(x.e.reconcile('pair:poly',stale.order,[]).reason,'STALE');assert.equal(x.e.pair('pair').cashFlowMicros,-610001);assert.throws(()=>x.e.preparePair('next',plan(),now),/halted|inventory/);}finally{x.close();}
});
test('Acknowledgments never create inventory; unknown submission cannot be retried or guessed from account data',()=>{
 const path=join(mkdtempSync(join(tmpdir(),'pilot-unknown-')),'p.sqlite'),e=new PilotExecutionLedger(path,'synthetic');try{e.preparePair('pair',plan(),now);assert.throws(()=>e.bindSubmissionResponse('pair:poly','personal-order'),/No owned submission/);e.beginSubmission('pair:poly',now);assert.throws(()=>e.beginSubmission('pair:poly',now),/cannot be submitted again/);assert.throws(()=>e.expected('pair:poly'),/outcome unknown/);e.bindSubmissionResponse('pair:poly','poly-order');const p=poly(0,'ORDER_STATE_NEW');e.reconcile('pair:poly',p.order,[]);assert.equal(e.pair('pair').matchedQuantity,0);assert.equal(e.pair('pair').cashFlowMicros,0);assert.equal(e.pair('pair').status,'AWAITING_ORDER_COMPLETION');}finally{e.close();}
});
test('Two completed legs produce owned paired inventory, not realized profit or reusable capital',()=>{
 const x=fixture();try{const k=kalshi(),p=poly(1,'ORDER_STATE_FILLED');x.e.reconcile('pair:kalshi',k.order,k.fills);x.e.reconcile('pair:poly',p.order,p.fills);assert.equal(x.e.pair('pair').status,'PAIRED_INVENTORY');assert.equal(x.e.pair('pair').cashFlowMicros,-810001);assert.equal(x.e.pair('pair').realizedProfitMicros,null);assert.throws(()=>x.e.preparePair('next',plan(),now),/inventory/);}finally{x.close();}
});
for(const variant of ['incomplete','conflict','over-budget','wrong-market'])test(`Invalid ${variant} evidence rolls back journal and intent together and persists a halt`,()=>{
 const x=fixture();try{const p=poly();if(variant==='incomplete')p.order.cumQuantity=1;if(variant==='over-budget'){p.fills[0].commissionNotionalCollected.value='1';p.order.commissionNotionalTotalCollected.value='1';}if(variant==='wrong-market')p.order.marketSlug='personal';
  if(variant==='conflict'){x.e.reconcile('pair:poly',p.order,p.fills);p.fills[0].lastShares='.25';}
  const before=x.e.ledger.get('pair:poly');assert.throws(()=>x.e.reconcile('pair:poly',p.order,p.fills));assert.deepEqual(x.e.ledger.get('pair:poly'),before);x.restart();assert.equal(x.e.pair('pair').status,'RECONCILIATION_BLOCKED');assert.equal((x.e.ledger.db.prepare('select halted from pilot_control').get() as any).halted,1);assert.ok((x.e.ledger.db.prepare("select body from pilot_execution_receipts where status='FAILED'").get() as any).body);
 }finally{x.close();}
});
test('Concurrent readers serialize duplicate accounting; evidence failure cannot erase accepted inventory',()=>{
 const x=fixture(),other=new PilotExecutionLedger(x.path,'synthetic');try{const p=poly();x.e.reconcile('pair:poly',p.order,p.fills);assert.equal(other.reconcile('pair:poly',p.order,p.fills).applied,false);assert.equal(other.pair('pair').cashFlowMicros,-200001);assert.throws(()=>other.reconcile('pair:poly',{...p.order,cumQuantity:1},[]));assert.equal(x.e.pair('pair').cashFlowMicros,-200001);}finally{other.close();x.close();}
});
test('Immutable identity, provenance, expired preflight and duplicate venue order binding fail closed',()=>{
 const x=fixture();try{assert.throws(()=>new PilotExecutionLedger(x.path,'live'),/mix/);assert.throws(()=>x.e.preparePair('new',plan(),now+250),/Fresh/);assert.throws(()=>x.e.bindSubmissionResponse('pair:poly','different'),/conflict/);assert.equal(x.e.pair('pair').liveSubmissionEnabled,false);}finally{x.close();}
});

import {DatabaseSync} from 'node:sqlite';
import {generateKeyPairSync} from 'node:crypto';
import {refreshOwnedIntent,ownedRawFills} from '../lib/pilot/order-refresh.ts';
test('Crash after receipt persistence is recoverable without resubmission or automatic halt clearing',()=>{
 const x=fixture();try{const p=poly();x.e.ledger.db.prepare("INSERT INTO pilot_execution_receipts(intent_id,body,status) VALUES(?,?,'PENDING')").run('pair:poly',JSON.stringify({order:p.order,fills:p.fills}));x.restart();assert.equal(x.e.pair('pair').status,'RECONCILIATION_BLOCKED');assert.equal(x.e.recoverPending(),1);assert.equal(x.e.recoverPending(),0);assert.equal(x.e.pair('pair').cashFlowMicros,-200001);assert.equal((x.e.ledger.db.prepare('select halted from pilot_control').get() as any).halted,1);assert.throws(()=>x.e.beginSubmission('pair:kalshi',now),/halted/);}finally{x.close();}
});
test('Database write failure rolls back journal, exact snapshot and reservation update as one unit',()=>{
 const x=fixture();try{x.e.ledger.db.exec("CREATE TRIGGER fail_snapshot BEFORE UPDATE OF snapshot ON pilot_execution_orders BEGIN SELECT RAISE(ABORT,'injected persistence failure'); END");const p=poly();assert.throws(()=>x.e.reconcile('pair:poly',p.order,p.fills),/injected/);assert.equal(x.e.journal.evidence('poly','poly-order').length,0);assert.equal(x.e.ledger.get('pair:poly').state,'SUBMISSION_UNKNOWN');assert.equal(x.e.pair('pair').cashFlowMicros,0);assert.equal(x.e.pair('pair').unappliedReceipts,1);}finally{x.close();}
});
test('Fill price cannot exceed the frozen order limit even while total debit fits reservation',()=>{
 const x=fixture();try{const p=poly();p.fills[0].lastPx.value='0.5999';assert.throws(()=>x.e.reconcile('pair:poly',p.order,p.fills),/immutable limit/);assert.equal(x.e.ledger.get('pair:poly').filled,0);}finally{x.close();}
});
test('Paper and research databases are rejected before pilot tables are added',()=>{
 const path=join(mkdtempSync(join(tmpdir(),'unrelated-db-')),'paper.sqlite');const db=new DatabaseSync(path);db.exec('CREATE TABLE paper_bot(body TEXT); INSERT INTO paper_bot VALUES(\'retained\')');db.close();assert.throws(()=>new PilotExecutionLedger(path,'live'),/unrelated/);const read=new DatabaseSync(path,{readOnly:true});try{assert.deepEqual(read.prepare("select name from sqlite_master where type='table'").all().map(r=>r.name),['paper_bot']);assert.equal(read.prepare('select body from paper_bot').get()!.body,'retained');}finally{read.close();}
});
function activity(fill:any,own=true){return {type:'ACTIVITY_TYPE_TRADE',trade:{marketSlug:'Pp',isAggressor:own,aggressorExecution:{...fill,aggressor:true},passiveExecution:{...fill,aggressor:false,order:{...fill.order,id:'personal-order'}}}};}
test('GET reconciliation selects only our account execution, reconciles exact money and is restart-idempotent',async()=>{
 const x=fixture();try{const p=poly(),key=generateKeyPairSync('ed25519').privateKey.export({type:'pkcs8',format:'der'}).subarray(-32);let calls=0;
 const options={env:{POLYMARKET_KEY_ID:'fixture',POLYMARKET_SECRET_KEY:key.toString('base64')},fetch:async(url:any,init:any)=>{calls++;assert.equal(init.method,'GET');assert.equal(init.redirect,'error');return new Response(JSON.stringify(String(url).includes('/order/')?{order:p.order}:{activities:[activity(p.fills[0]),activity(p.fills[0],false)],eof:true,nextCursor:''}));}};
 await refreshOwnedIntent(x.e,'pair:poly',options as any);assert.equal(x.e.pair('pair').cashFlowMicros,-200001);x.restart();assert.equal((await refreshOwnedIntent(x.e,'pair:poly',options as any)).reason,'DUPLICATE');assert.equal(calls,4);
 }finally{x.close();}
});
test('Incomplete pagination and counterparty ownership cannot manufacture no-fill evidence',()=>{
 const p=poly(),expected={orderId:'poly-order',marketId:'Pp',side:'no',action:'buy'} as const;
 assert.throws(()=>ownedRawFills('poly',expected,{activities:[],eof:false,nextCursor:'more'}),/Incomplete/);
 assert.throws(()=>ownedRawFills('kalshi',expected,{fills:[],cursor:'more'}),/Incomplete/);
 assert.deepEqual(ownedRawFills('poly',expected,{activities:[activity(p.fills[0],false)],eof:true,nextCursor:''}),[]);
 const bad=activity(p.fills[0]);bad.trade.aggressorExecution.aggressor=false;assert.throws(()=>ownedRawFills('poly',expected,{activities:[bad],eof:true,nextCursor:''}),/ownership/);
});
test('An authoritative GET failure halts while retaining existing exposure',async()=>{
 const x=fixture();try{const p=poly();x.e.reconcile('pair:poly',p.order,p.fills);await assert.rejects(refreshOwnedIntent(x.e,'pair:poly',{env:{}}));assert.equal(x.e.pair('pair').cashFlowMicros,-200001);assert.equal((x.e.ledger.db.prepare('select halted from pilot_control').get() as any).halted,1);}finally{x.close();}
});

test('Equivalent source timestamp formats deduplicate and recovery summaries expose persistent halt',()=>{
 const x=fixture();try{const p=poly();x.e.reconcile('pair:poly',p.order,p.fills);p.order.lastTransactTime='2026-09-14T18:00:00.000Z';assert.equal(x.e.reconcile('pair:poly',p.order,p.fills).reason,'DUPLICATE');x.e.ledger.halt('REVIEW_REQUIRED');x.restart();assert.equal(x.e.pair('pair').halted,true);assert.equal(x.e.pair('pair').haltReason,'REVIEW_REQUIRED');assert.equal(x.e.pair('pair').accountingComplete,false);}finally{x.close();}
});

const wireMetadata={kalshi:{marketId:'Kp',tick:100,minimumQuantity:1,exchangeIndex:0},poly:{marketId:'Pp',tick:100,minimumQuantity:1}};
test('Outbound journal atomically stages both FOK requests before any sender and cannot stage again after restart',()=>{
 const path=join(mkdtempSync(join(tmpdir(),'pilot-dispatch-')),'p.sqlite');let e=new PilotExecutionLedger(path,'synthetic');try{e.preparePair('pair',plan(),now);baselines(e);const dispatch=e.stagePairDispatch('pair',wireMetadata,now);assert.equal(dispatch.liveSubmissionEnabled,false);assert.equal(dispatch.requests.length,2);for(const r of dispatch.requests)assert.equal(e.ledger.get(r.intentId).state,'SUBMISSION_UNKNOWN');e.close();e=new PilotExecutionLedger(path,'synthetic');assert.equal(e.stagedDispatch('pair:kalshi')?.wire.body.time_in_force,'fill_or_kill');assert.equal(e.stagedDispatch('pair:poly')?.wire.body.tif,'TIME_IN_FORCE_FILL_OR_KILL');assert.throws(()=>e.stagePairDispatch('pair',wireMetadata,now),/cannot be submitted again/);assert.equal(e.recovery('pair').action,'RESOLVE_SUBMISSION_IDENTITY');assert.equal(e.recovery('pair').inventoryMayIncrease,true);assert.equal(e.recovery('pair').automaticRetryAllowed,false);}finally{e.close();}
});
test('Bad second wire, expired plan and second write failure leave BOTH intents reserved and no dispatch journal',()=>{
 for(const failure of ['metadata','expired','write']){const e=new PilotExecutionLedger(':memory:','synthetic');try{e.preparePair('pair',plan(),now);baselines(e);if(failure==='write')e.ledger.db.exec("CREATE TRIGGER fail_dispatch BEFORE INSERT ON pilot_execution_dispatches WHEN NEW.intent_id='pair:poly' BEGIN SELECT RAISE(ABORT,'injected dispatch failure'); END");assert.throws(()=>e.stagePairDispatch('pair',failure==='metadata'?{...wireMetadata,poly:{...wireMetadata.poly,tick:333}}:wireMetadata,failure==='expired'?now+250:now));for(const v of ['kalshi','poly']){assert.equal(e.ledger.get('pair:'+v).state,'RESERVED');assert.equal(e.stagedDispatch('pair:'+v),null);}}finally{e.close();}}
});
test('Full fill versus terminal zero fill halts and yields exact recovery inventory, never a new hedge order',()=>{
 const x=fixture();try{const k=kalshi(),p=poly(0);x.e.reconcile('pair:kalshi',k.order,k.fills);assert.equal(x.e.recovery('pair').action,'RECONCILE_OPEN_ORDERS');assert.equal(x.e.recovery('pair').inventoryMayIncrease,true);x.e.reconcile('pair:poly',p.order,[]);x.restart();assert.equal(x.e.pair('pair').halted,true);const r=x.e.recovery('pair');assert.equal(r.action,'PLAN_EXPOSURE_RECOVERY');assert.deepEqual(r.acceptedExcessInventory,[{intentId:'pair:kalshi',venue:'kalshi',quantity:1}]);assert.equal(r.inventoryMayIncrease,false);assert.equal(r.automaticRecoveryAllowed,false);}finally{x.close();}
});
test('Rejected evidence takes recovery priority over accepted inventory and never permits an automatic unwind',()=>{
 const x=fixture();try{const p=poly();x.e.reconcile('pair:poly',p.order,p.fills);assert.throws(()=>x.e.reconcile('pair:poly',{...p.order,cumQuantity:1},[]));assert.equal(x.e.recovery('pair').action,'REVIEW_UNAPPLIED_EVIDENCE');assert.equal(x.e.recovery('pair').inventoryMayIncrease,true);assert.equal(x.e.recovery('pair').acceptedExcessInventory[0].quantity,.5);}finally{x.close();}
});

test('Settlement assessment uses durable owned fills and refuses unreconciled or personal inventory without releasing cash',()=>{
 const x=fixture();try{const k=kalshi(),record={ticker:'Kp',exchange_index:0,market_result:'yes',yes_count_fp:'1',no_count_fp:'0',yes_total_cost_dollars:'0.4',no_total_cost_dollars:'0',fee_cost:'0.01',revenue:100,settled_time:'2026-09-14T19:00:00Z'},market={ticker:'Kp',status:'finalized',result:'yes',settlement_value_dollars:'1',settlement_ts:'2026-09-14T19:00:00Z'};assert.throws(()=>x.e.assessKalshiSettlement('pair:kalshi',record,market,k.fills));x.e.reconcile('pair:kalshi',k.order,k.fills);const before=x.e.pair('pair'),e=x.e.assessKalshiSettlement('pair:kalshi',record,market,k.fills);assert.equal(e.payoutMicros,1000000);assert.equal(e.creditAuthorized,false);assert.deepEqual(x.e.pair('pair'),before);assert.throws(()=>x.e.assessKalshiSettlement('pair:kalshi',record,market,[...k.fills,{...k.fills[0],fill_id:'personal'}]),/ownership/);assert.throws(()=>x.e.assessKalshiSettlement('pair:poly',record,market,k.fills));}finally{x.close();}
});

function baselines(e:PilotExecutionLedger){for(const v of ['kalshi','poly'] as const)e.recordCashObservation(v,v,v==='kalshi'?{balance_dollars:'100.000001'}:{balances:[{currency:'USD',currentBalance:'100.000001',buyingPower:'99'}]},{startedAt:now-100,finishedAt:now-50,elapsedMs:50},'a'.repeat(64));e.linkPairCashBaselines('pair',{kalshi:'kalshi',poly:'poly'});}
test('Cash observations persist exact values, reject conflicting replay and cannot be backfilled after submission',()=>{const path=join(mkdtempSync(join(tmpdir(),'pilot-cash-')),'p.sqlite');let e=new PilotExecutionLedger(path,'synthetic');try{e.preparePair('pair',plan(),now);assert.throws(()=>e.stagePairDispatch('pair',wireMetadata,now),/baselines/);baselines(e);assert.throws(()=>e.recordCashObservation('kalshi','kalshi',{balance_dollars:'999'},{startedAt:now-100,finishedAt:now-50,elapsedMs:50},'a'.repeat(64)),/conflict/);e.close();e=new PilotExecutionLedger(path,'synthetic');const row=e.ledger.db.prepare('select body from pilot_cash_observations where id=?').get('kalshi') as {body:string};assert.equal(JSON.parse(row.body).cashMicros,100000001);e.stagePairDispatch('pair',wireMetadata,now);assert.throws(()=>e.linkPairCashBaselines('pair',{kalshi:'kalshi',poly:'poly'}),/backfill/);}finally{e.close();}});
test('Baseline timing and second venue failure roll back the entire link',()=>{const e=new PilotExecutionLedger(':memory:','synthetic');try{e.preparePair('pair',plan(),now);e.recordCashObservation('late','kalshi',{balance_dollars:'100'},{startedAt:now+1,finishedAt:now+2,elapsedMs:1},'a'.repeat(64));assert.throws(()=>e.linkPairCashBaselines('pair',{kalshi:'late',poly:'missing'}),/precede/);e.recordCashObservation('early','kalshi',{balance_dollars:'100'},{startedAt:now-100,finishedAt:now-50,elapsedMs:50},'a'.repeat(64));assert.throws(()=>e.linkPairCashBaselines('pair',{kalshi:'early',poly:'missing'}),/Missing/);assert.equal((e.ledger.db.prepare('select count(*) n from pilot_cash_baselines').get() as {n:number}).n,0);}finally{e.close();}});

test('Durable settlement expectation joins cash audit once without converting an expectation into realized profit',()=>{
 const x=fixture();try{const p=poly();(p.fills[0] as any).aggressor=true;const activity={type:'ACTIVITY_TYPE_TRADE',trade:{marketSlug:'Pp',isAggressor:true,createTime:'2026-09-14T18:00:00Z',updateTime:'2026-09-14T18:00:00Z',aggressorExecution:p.fills[0]}};x.e.reconcile('pair:poly',p.order,p.fills);
 const usd=(value:string)=>({value,currency:'USD'}),before={netPositionDecimal:'-0.5',qtyBoughtDecimal:'0.5',qtySoldDecimal:'0',cost:usd('0.2'),realized:usd('0'),cashValue:usd('0.5')};
 const record={type:'ACTIVITY_TYPE_POSITION_RESOLUTION',positionResolution:{marketSlug:'Pp',side:'POSITION_RESOLUTION_SIDE_SHORT',market:{slug:'Pp',closed:true,status:'MARKET_STATUS_RESOLVED'},updateTime:'2026-09-14T18:00:01Z',beforePosition:before,afterPosition:{...before,netPositionDecimal:'0',qtySoldDecimal:'0.5',cashValue:usd('0')}}},published={slug:'Pp',settlement:0};
 const e=x.e.recordPolySettlementExpectation('pair:poly',record,published,[activity]);assert.equal(e.expectedPayoutMicros,500000);x.restart();assert.deepEqual(x.e.recordPolySettlementExpectation('pair:poly',record,published,[activity]),e);assert.throws(()=>x.e.recordPolySettlementExpectation('pair:poly',record,{...published,settlement:1},[activity]),/conflict/);
 const at=Date.parse('2026-09-14T18:00:00Z');for(const [id,cash,start] of [['before','10',at-1000],['after','10.299999',at+2000]] as const)x.e.recordCashObservation(id,'poly',{balances:[{currency:'USD',currentBalance:cash,buyingPower:cash}]},{startedAt:start,finishedAt:start+10,elapsedMs:10},'a'.repeat(64));
 const r=x.e.recordPolyCashAudit('joined','before','after',[activity,record,structuredClone(record)]);assert.equal(r.status,'CONSISTENT_WITH_CLASSIFIED_CASH');assert.equal(r.expectedSettlementMicros,500000);assert.equal(r.ownedTradeCashFlowMicros,-200001);assert.equal(r.realizedProfitMicros,null);assert.equal(r.creditAuthorized,false);assert.equal(x.e.pair('pair').realizedProfitMicros,null);x.restart();assert.deepEqual(x.e.recordPolyCashAudit('joined','before','after',[activity,record,structuredClone(record)]),r);
 const foreign=structuredClone(activity);foreign.trade.aggressorExecution.id='foreign';foreign.trade.aggressorExecution.order.id='foreign';assert.throws(()=>x.e.recordPolyCashAudit('foreign','before','after',[activity,record,foreign]));
 }finally{x.close();}
});
