import {test} from 'node:test';import assert from 'node:assert/strict';
import {reconcileKalshiSettlement} from '../lib/pilot/settlement-evidence.ts';
function fixture(result='yes'){
 const fill={fill_id:'fill',order_id:'bot',ticker:'K',market_ticker:'K',side:'yes',outcome_side:'yes',action:'buy',book_side:'bid',exchange_index:0,subaccount_number:0,count_fp:'1',yes_price_dollars:'.4',no_price_dollars:'0.6',fee_cost:'0.01'};fill.yes_price_dollars='0.4';
 return {expected:{orderId:'bot',marketId:'K',side:'yes' as const,action:'buy' as const},ownedFillIds:['fill'],accountFills:[fill],record:{ticker:'K',exchange_index:0,market_result:result,yes_count_fp:'1',no_count_fp:'0',yes_total_cost_dollars:'0.4',no_total_cost_dollars:'0',fee_cost:'0.01',revenue:result==='yes'?100:0,settled_time:'2026-09-14T18:00:00Z'},market:{ticker:'K',status:'finalized',result,settlement_value_dollars:result==='yes'?'1':'0',settlement_ts:'2026-09-14T18:00:00Z'}};
}
test('Payout assessment subtracts entry debit once, keeps fee exact and never authorizes account credit',()=>{const r=reconcileKalshiSettlement(fixture());assert.equal(r.payoutMicros,1000000);assert.equal(r.netCashFlowMicros,590000);assert.equal(r.feeMicros,10000);assert.equal(r.creditAuthorized,false);assert.equal(r.accountCashReconciled,false);});
test('Zero payout retains the full entry loss, including fees',()=>{const r=reconcileKalshiSettlement(fixture('no'));assert.equal(r.payoutMicros,0);assert.equal(r.netCashFlowMicros,-410000);});
test('Duplicate identical fills do not increase payout; conflicting duplicates fail',()=>{const x=fixture();x.accountFills.push({...x.accountFills[0]});assert.equal(reconcileKalshiSettlement(x).quantityUnits,10000);x.accountFills[1].fee_cost='0.02';assert.throws(()=>reconcileKalshiSettlement(x));});
test('Personal orders, missing owned fills and opposite inventory cannot become bot settlement',()=>{for(const mode of ['personal','missing','opposite']){const x=fixture();if(mode==='personal')x.accountFills.push({...x.accountFills[0],fill_id:'personal',order_id:'user'});if(mode==='missing')x.accountFills=[];if(mode==='opposite')x.record.no_count_fp='1';assert.throws(()=>reconcileKalshiSettlement(x));}});
test('Non-final, scalar, wrong identity and unsupported cash precision fail closed',()=>{for(const mode of ['open','scalar','identity','precision']){const x=fixture();if(mode==='open')x.market.status='determined';if(mode==='scalar')x.record.market_result='scalar';if(mode==='identity')x.market.ticker='other';if(mode==='precision')x.record.fee_cost='0.0100001';assert.throws(()=>reconcileKalshiSettlement(x));}});
test('Wrong payout, fee, notional and revenue type cannot manufacture settlement profit',()=>{for(const mode of ['payout','fee','notional','revenue']){const x=fixture();if(mode==='payout')x.record.revenue=99;if(mode==='fee')x.record.fee_cost='0';if(mode==='notional')x.record.yes_total_cost_dollars='0.3';if(mode==='revenue')(x.record as any).revenue='100';assert.throws(()=>reconcileKalshiSettlement(x));}});
