"use client";
import {useState,useEffect,useRef} from 'react';
import Scanner from './scanner';
import Journal from './journal';
import {api} from './client-api';
import {totals} from '@/lib/arb/ledger';
import type {State} from '@/lib/arb/types';
import type {Discovery} from '@/lib/arb/adapters';
import type {ScanRow} from './scanner';
import {Zap, Radar, ArrowUpRight, Calculator, ShieldCheck, BookOpen, CirclePause,Play,RefreshCw,X} from 'lucide-react';
import {Tabs, TabsList, TabsTrigger, TabsContent} from '@/components/ui/tabs';
import {Progress} from '@/components/ui/progress';
import {calculate, money} from '@/lib/arb/core';
export default function Dashboard(){
 const [state,setState]=useState<State|null>(null),[discovery,setDiscovery]=useState<(Discovery&{suggestions:import('@/lib/arb/types').Pair[]})|null>(null),[rows,setRows]=useState<ScanRow[]>([]),[busy,setBusy]=useState(false),[running,setRunning]=useState(false),[message,setMessage]=useState(''),[signedOut,setSignedOut]=useState(false),[clock,setClock]=useState(Date.now());
 const active=useRef(false);
 const summary=state?totals(state):{cash:1000000,committed:0,realized:0,equity:1000000};
 const day=state?.startedAt?Math.min(30,Math.floor((clock-state.startedAt)/86400000)+1):0;
 async function scan(){if(active.current)return;active.current=true;setBusy(true);try{const d=await api('scan');setRows(d.rows);}catch(e){setMessage((e as Error).message);}finally{active.current=false;setBusy(false);}}
 async function discover(){if(active.current)return;active.current=true;setBusy(true);setMessage('');try{setDiscovery(await api('discover'));}catch(e){setMessage((e as Error).message);}finally{active.current=false;setBusy(false);}}
 async function cycle(settleOnly=false){if(active.current)return;active.current=true;setBusy(true);setMessage('');try{const next=await api<State>('run',{settleOnly});setState(next);if(next.positions.some(p=>p.status==='unmatched')||next.logs[0]?.kind==='failed hedge')setRunning(false);const d=await api('scan');setRows(d.rows);}catch(e){if(!(e as Error).message.includes('30 seconds'))setRunning(false);setMessage((e as Error).message);}finally{active.current=false;setBusy(false);}}
 async function start(){if(running){setRunning(false);return;}try{if(!state?.startedAt)setState(await api('state',{action:'start'}));setRunning(true);await cycle();}catch(e){setMessage((e as Error).message);}}
 useEffect(()=>{api<State>('state').then(setState).catch(e=>{setMessage(e.message);setSignedOut(e.message.startsWith('Sign in'));});const t=setInterval(()=>setClock(Date.now()),1000);return()=>clearInterval(t);},[]);
 useEffect(()=>{if(!running)return;const t=setInterval(()=>void cycle(),30000);return()=>clearInterval(t);},[running]);
 useEffect(()=>{
  type Tool={name:string;description:string;inputSchema:object;annotations:object;execute:(input:any)=>any};
  const ctx=(document as unknown as {modelContext?:{registerTool:(t:Tool,o:{signal:AbortSignal})=>void}}).modelContext;if(!ctx)return;const lifecycle=new AbortController();
  try{ctx.registerTool({name:'calculate_arbitrage',description:'Calculate a hypothetical two-leg trade after default fees and update the visible calculator inputs. Does not trade or change the paper ledger.',inputSchema:{type:'object',properties:{kalshiCents:{type:'number'},polyCents:{type:'number'},quantity:{type:'integer'}},required:['kalshiCents','polyCents','quantity'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(x)=>{const result=calculate(Math.round(x.kalshiCents*100),Math.round(x.polyCents*100),x.quantity);setA(String(x.kalshiCents));setB(String(x.polyCents));setQ(String(x.quantity));setTab('calculator');return result;}},{signal:lifecycle.signal});}catch{}return()=>lifecycle.abort();
 },[]);
 const [tab,setTab]=useState('scanner');
 const [a,setA]=useState('40'),[b,setB]=useState('50'),[q,setQ]=useState('10');
 let quote; try {quote=calculate(Math.round(Number(a)*100),Math.round(Number(b)*100),Number(q));}catch{}
 return <main className="shell">
 <header className="topbar"><a className="brand" href="/"><span className="brand-icon"><Zap size={23} fill="currentColor"/></span>LIGHTS ON<span className="edition">/ ARBITRAGE LAB</span></a><div className="topmeta"><span className="tag">OHIO · US VENUES</span><span className="paper-badge">PAPER MODE</span></div></header>
 <div className="workspace"><div className="page-heading"><div><div className="eyebrow">THE $100 → $1,000 EXPERIMENT</div><h1>Every cent has a job.</h1><p>Find the gap. Check the cost. Keep the lights on.</p></div><button className={running?"secondary":"primary"} disabled={busy||!state} onClick={start}>{running?<CirclePause size={16}/>:<Play size={16}/>} {running?"Pause paper bot":state?.startedAt?"Run paper bot":"Start paper challenge"}</button></div>
 {message&&<div className="alert-bar" role="status"><span>{message}{signedOut&&<a href="/signin-with-chatgpt?return_to=/" target="_top"> Sign in with ChatGPT →</a>}</span><button className="icon-button" aria-label="Dismiss message" onClick={()=>setMessage('')}><X size={16}/></button></div>}
 <div className="runtime-bar"><span>{running?'PAPER BOT RUNNING · 30s cycles':busy?'FETCHING PUBLIC DATA':'PAPER BOT PAUSED'}</span><span>Live-data research · no real orders · {state?'Ledger saved privately':'Loading private ledger'}</span></div>
 <section className="scoreboard"><div className="bankroll"><span className="eyebrow">PAPER EQUITY · AT COST</span><strong>{money(summary.equity)}</strong><span className="muted">{money(state?.cash.kalshi??500000)} K <span className="divider">/</span> {money(state?.cash.poly??500000)} PUS</span></div><div className="score"><span>Realized profit</span><strong className={summary.realized>0?"accent":""}>{money(summary.realized)}</strong><small>After recorded costs</small></div><div className="score"><span>Capital committed</span><strong>{money(summary.committed)}</strong><small>{money(summary.cash)} available</small></div><div className="mission"><div><span className="eyebrow">30-DAY CHALLENGE</span><span className="tag">{day?`DAY ${day} / 30`:"READY"}</span></div><h3>{money(Math.max(0,9000000-summary.realized))} <span>to the target</span></h3><Progress value={Math.min(100,Math.max(0,summary.realized/90000))}/><div className="mission-foot"><span>$100 start</span><span>$1,000 stretch goal</span></div></div></section>
 <Tabs value={tab} onValueChange={setTab}><TabsList className="navigation" variant="line"><TabsTrigger value="scanner"><Radar/>Opportunity scanner</TabsTrigger><TabsTrigger value="calculator"><Calculator/>Arb calculator</TabsTrigger><TabsTrigger value="journal"><BookOpen/>Paper journal</TabsTrigger></TabsList>
 <TabsContent value="calculator"><div className="content-grid"><section className="panel"><div className="panel-head"><div><h2>Two legs. One calculation.</h2><p>Try prices before committing capital.</p></div><span className="tag">HYPOTHETICAL</span></div><div className="calculator-inputs"><label>Kalshi YES · cents<input type="number" min="0.01" max="99.99" step="0.01" value={a} onChange={e=>setA(e.target.value)}/></label><label>Polymarket US NO · cents<input type="number" min="0.01" max="99.99" step="0.01" value={b} onChange={e=>setB(e.target.value)}/></label><label>Paired contracts<input type="number" min="1" max="1000000" value={q} onChange={e=>setQ(e.target.value)}/></label></div>{quote?<><div className="leg-grid"><div className="leg"><span className="venue kalshi">K</span><div><span className="muted">LEG 01 · KALSHI</span><h3>Buy YES</h3></div><strong>{a}¢</strong></div><div className="leg"><span className="venue poly">P</span><div><span className="muted">LEG 02 · POLYMARKET US</span><h3>Buy NO</h3></div><strong>{b}¢</strong></div></div><div className="cost-lines"><div><span>Combined purchase</span><b>{money(quote.cost)}</b></div><div><span>Estimated taker fees</span><b>{money(quote.fees)}</b></div><div><span>Execution reserve · 1¢ / pair</span><b>{money(quote.reserve)}</b></div><div><span>Conditional settlement payout</span><b>{money(quote.payout)}</b></div></div><div className={'net-result '+(quote.profit>0?'positive':'negative')}><div><span>NET MODELED PROFIT</span><strong>{money(quote.profit)}</strong></div><span>{quote.roi.toFixed(2)}% return<ArrowUpRight size={20}/></span></div></>:<p className="notice">Enter valid prices and a positive whole number of contracts.</p>}<p className="fine-print">Assumes equivalent settlement rules and both legs filled. Uses Kalshi general fees and the Polymarket US July 2026 schedule. Actual product fees and liquidity must be checked.</p></section><aside className="panel strategy"><ShieldCheck className="accent" size={26}/><h2>The edge is what’s left.</h2><p>A price gap is only the beginning. Fees, fillable size, and settlement rules decide whether it survives.</p><ol><li><span>01</span>Same event and settlement rules</li><li><span>02</span>Enough depth on both sides</li><li><span>03</span>Profit after every cost</li><li><span>04</span>Cash available at each venue</li></ol><div className="notice">Ohio research profile. Sports excluded pending verification. Real-money execution is disabled.</div></aside></div></TabsContent>
 <TabsContent value="scanner"><Scanner state={state} discovery={discovery} rows={rows} busy={busy} onDiscover={discover} onScan={scan} onState={setState} onError={setMessage}/></TabsContent>
 <TabsContent value="journal"><Journal state={state} onState={setState} onError={setMessage} onSettle={()=>cycle(true)} busy={busy}/></TabsContent>
 </Tabs><footer><span><Zap size={14}/>LIGHTS ON · EXPERIMENT 001</span><span>Target ≠ forecast. Paper results ≠ actual fills.</span></footer></div></main>;
}
