'use client';
import {useState} from 'react';import {Download,BookOpen,Settings2,Receipt} from 'lucide-react';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import type {State} from '@/lib/arb/types';import {money} from '@/lib/arb/core';import {api} from './client-api';
export default function Journal({state,onState,onError,onSettle,busy}:{state:State|null;onState:(s:State)=>void;onError:(s:string)=>void;onSettle:()=>void;busy:boolean}){
 const [expense,setExpense]=useState(''),[saving,setSaving]=useState(false);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!state)return;setSaving(true);const data=new FormData(e.currentTarget);try{const settings={...state.settings,maxTrade:Math.round(Number(data.get('maxTrade'))*10000),maxCommitted:Math.round(Number(data.get('maxCommitted'))*10000),minProfit:Math.round(Number(data.get('minProfit'))*10000),minRoi:Number(data.get('minRoi')),reserve:Math.round(Number(data.get('reserve'))*100),maxDays:Number(data.get('maxDays'))};onState(await api('state',{action:'settings',settings}));}catch(e){onError((e as Error).message);}finally{setSaving(false);}}
 function exportCSV(){if(!state)return;const quote=(x:unknown)=>'"'+String(x??'').replace(/"/g,'""').replace(/^[=+@-]/,"'")+ '"';const rows=[['ID','Status','Kalshi','Polymarket US','Quantity','Kalshi side','Polymarket side','Debited USD','Realized profit USD','Opened','Closed'],...state.positions.map(p=>[p.id,p.status,p.pair.a.id,p.pair.b.id,p.quote.quantity,p.quote.aSide,p.quote.bSide,(p.aDebit+p.bDebit)/10000,p.profit===undefined?'':p.profit/10000,new Date(p.openedAt).toISOString(),p.closedAt?new Date(p.closedAt).toISOString():''])];const blob=new Blob([rows.map(r=>r.map(quote).join(',')).join('\n')],{type:'text/csv'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='lights-on-paper-journal.csv';a.click();URL.revokeObjectURL(url);}
 return <div className="content-grid"><div><section className="panel"><div className="panel-head"><div><h2>Paper journal</h2><p>{state?.provenance==='synthetic'?'Synthetic entries and synthetic settlements. No market pair is approved by this demo.':'Simulated entries, actual published settlement results.'}</p></div><button className="secondary" disabled={!state} onClick={exportCSV}><Download size={15}/>Export CSV</button></div>
 {state?.positions.length?<Table><TableHeader><TableRow><TableHead>CONTRACT</TableHead><TableHead>OUTLAY</TableHead><TableHead>REALIZED</TableHead><TableHead>STATE</TableHead></TableRow></TableHeader><TableBody>{state.positions.map(p=><TableRow key={p.id}><TableCell className="journal-title"><b>{p.pair.a.title}</b><small className="table-meta">{p.quote.quantity} pairs · {new Date(p.openedAt).toLocaleString()}</small></TableCell><TableCell>{money(p.aDebit+p.bDebit)}</TableCell><TableCell className={p.profit&&p.profit>0?'accent':''}>{p.profit===undefined?'Pending':money(p.profit)}</TableCell><TableCell><span className="state-wait">{p.status}</span></TableCell></TableRow>)}</TableBody></Table>:<div className="empty-state compact"><BookOpen size={34}/><h2>A clean starting line</h2><p>When a reviewed pair clears the entry checks, its simulated fills and eventual settlements appear here.</p></div>}
 <button className="text-button" disabled={busy||!state?.startedAt} onClick={onSettle}>{state?.provenance==='synthetic'?'Check synthetic settlements':'Check published settlements'}</button><p className="fine-print">Equity uses the cost of unsettled positions, not a live liquidation value. The execution reserve is charged as a simulated cost. Hypothetical calculator results never enter this ledger.</p></section>
 <section className="panel activity"><h2>Activity log</h2>{state?.logs.length?state.logs.slice(0,25).map(l=><div className="log-row" key={l.id}><time>{new Date(l.at).toLocaleTimeString()}</time><div><b>{l.kind}</b><p>{l.message}</p></div></div>):<p className="fine-print">The experiment has not started.</p>}</section></div>
 <aside><section className="panel"><div className="panel-head"><h2><Settings2 size={18}/>Paper limits</h2></div>{state&&<form className="limits-form" onSubmit={submit} key={JSON.stringify(state.settings)}>{[['maxTrade','Maximum per pair · $',state.settings.maxTrade/10000,1,100,.01],['maxCommitted','Total committed · $',state.settings.maxCommitted/10000,1,100,.01],['minProfit','Minimum net profit · $',state.settings.minProfit/10000,.01,10,.01],['minRoi','Minimum return · %',state.settings.minRoi,1,50,1],['reserve','Execution reserve · ¢ / pair',state.settings.reserve/100,1,10,1],['maxDays','Maximum days to settlement',state.settings.maxDays,1,30,1]].map(([name,label,value,min,max,step])=><label className="field" key={String(name)}>{label}<input name={String(name)} type="number" required defaultValue={value} min={min} max={max} step={step}/></label>)}<button className="primary" disabled={saving}>{saving?'Saving…':'Save paper limits'}</button></form>}<p className="fine-print">Whole contracts only. Quotes expire after 2 seconds. New entries stop after a $5 realized loss per UTC day, unmatched exposure, or day 30. Open positions still need settlement checks.</p></section>
 <section className="panel activity"><h2><Receipt size={18}/>Operating costs</h2><p className="fine-print">Count hosting, subscriptions, and other expenses against the experiment. Debited from Kalshi paper cash.</p><div className="expense-input"><input aria-label="Operating expense in dollars" type="number" min="0.01" step="0.01" placeholder="Amount · $" value={expense} onChange={e=>setExpense(e.target.value)}/><button className="secondary" disabled={!state||saving||Number(expense)<=0} onClick={async()=>{setSaving(true);try{onState(await api('state',{action:'expense',amount:Math.round(Number(expense)*10000)}));setExpense('');}catch(e){onError((e as Error).message);}finally{setSaving(false);}}}>Record</button></div><p className="fine-print">Recorded: {money(state?.expenses||0)}</p></section></aside></div>;
}
