'use client';
import {useState} from 'react';
import {Radar,RefreshCw,Search,ArrowUpRight,ShieldCheck,Plus,Trash2,Check,ExternalLink} from 'lucide-react';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Checkbox} from '@/components/ui/checkbox';
import {Switch} from '@/components/ui/switch';
import {api} from './client-api';
import {money} from '@/lib/arb/core';
import type {State,Pair,Quote,Market,Book} from '@/lib/arb/types';
import type {Discovery} from '@/lib/arb/adapters';
export type ScanRow={pair:Pair;quote:Quote|null;error?:string|null;books?:{a:Book;b:Book}};
export default function Scanner({state,discovery,rows,busy,onDiscover,onScan,onState,onError}:{state:State|null;discovery:(Discovery&{suggestions:Pair[]})|null;rows:ScanRow[];busy:boolean;onDiscover:()=>void;onScan:()=>void;onState:(s:State)=>void;onError:(s:string)=>void}){
 const [search,setSearch]=useState(''),[inspect,setInspect]=useState<Pair|null>(null),[loading,setLoading]=useState(false),[manual,setManual]=useState(false),[k,setK]=useState(''),[p,setP]=useState(''),[checks,setChecks]=useState([false,false,false]),[inverted,setInverted]=useState(false),[notes,setNotes]=useState('');
 async function view(kalshi:string,poly:string){setLoading(true);setChecks([false,false,false]);try{const d=await api('pair',{kalshi,poly});setInspect(d.pair);setInverted(false);setNotes('');setManual(false);}catch(e){onError(String(e instanceof Error?e.message:e));}finally{setLoading(false);}}
 async function approve(){if(!inspect)return;setLoading(true);try{const d=await api('pair',{action:'review',kalshi:inspect.a.id,poly:inspect.b.id,aHash:inspect.a.hash,bHash:inspect.b.hash,inverted,rulesChecked:checks[0],outcomesChecked:checks[1],voidChecked:checks[2],notes});onState(d.state);setInspect(null);onScan();}catch(e){onError((e as Error).message);}finally{setLoading(false);}}
 const suggestions=(discovery?.suggestions||[]).filter(x=>!state?.pairs.some(y=>x.id===y.id)&&(`${x.a.title} ${x.b.title}`).toLowerCase().includes(search.toLowerCase()));
 const watched=state?.pairs.filter(x=>(`${x.a.title} ${x.b.title}`).toLowerCase().includes(search.toLowerCase()))||[];
 const filteredMarkets=[...(discovery?.kalshi||[]),...(discovery?.poly||[])].filter(m=>(m.title+' '+m.id).toLowerCase().includes(search.toLowerCase())).slice(0,20);
 return <><div className="source-strip"><div><span className="venue kalshi">K</span><div><b>Kalshi</b><span>{discovery?`${discovery.kalshi.length} open non-sports markets`:'Public feed · ready to connect'}</span></div></div><div><span className="venue poly">P</span><div><b>Polymarket US</b><span>{discovery?`${discovery.poly.length} open non-sports markets`:'U.S. public feed · no keys needed'}</span></div></div><div className="source-note">REST snapshots<span>{discovery?`Discovery ${new Date(discovery.at).toLocaleTimeString()}`:'Click Discover markets to load'}</span></div></div>
 <div className="content-grid scanner-grid"><section className="panel scanner-panel"><div className="panel-head"><div><h2>Opportunity scanner <span className="count">{watched.length}</span></h2><p>Reviewed pairs first. Only the net edge counts.</p></div><button className="secondary" onClick={onScan} disabled={busy||!state?.pairs.length}><RefreshCw size={15}/>Refresh books</button></div>
 <div className="scan-controls"><div className="searchbox"><Search size={16}/><input aria-label="Search markets" placeholder="Search events or market IDs…" value={search} onChange={e=>setSearch(e.target.value)}/></div><button className="secondary" onClick={onDiscover} disabled={busy||!state}><Radar size={15}/>{busy?'Working…':'Discover markets'}</button></div>
 {discovery?.errors.map((e,i)=><div key={i} className="notice">{e}</div>)}
 <Table><TableHeader><TableRow><TableHead>EVENT / CONTRACT</TableHead><TableHead>NET EDGE</TableHead><TableHead>STATUS</TableHead><TableHead><span className="sr-only">Actions</span></TableHead></TableRow></TableHeader><TableBody>{watched.map(pair=>{const r=rows.find(x=>x.pair.id===pair.id),q=r?.quote;return <TableRow key={pair.id}><TableCell><button className="event-button" onClick={()=>view(pair.a.id,pair.b.id)}><b>{pair.a.title}</b><small>{pair.b.title}</small></button><span className="pair-label">KALSHI ↔ POLYMARKET US</span></TableCell><TableCell><strong className={q&&q.profit>0?'accent':''}>{q?money(q.profit):'—'}</strong><small className="table-meta">{q?`${q.quantity} pairs · ${q.roi.toFixed(2)}%`:'Refresh to price'}</small></TableCell><TableCell><span className={q?.eligible?'state-good':'state-wait'}>{q?.eligible?'Paper eligible':q?.reasons[0]||r?.error||'Awaiting book'}</span>{q&&<small className="table-meta">Observed {new Date(q.receivedAt).toLocaleTimeString()}</small>}</TableCell><TableCell><button className="icon-button" aria-label={`Remove ${pair.a.title}`} onClick={async()=>{try{onState(await api('state',{action:'remove',pairId:pair.id}));}catch(e){onError((e as Error).message);}}}><Trash2 size={15}/></button></TableCell></TableRow>})}</TableBody></Table>
 {!watched.length&&<div className="empty-state compact"><Radar size={35}/><h2>No reviewed pairs yet</h2><p>Discover matching candidates, inspect both settlement rules, then add a pair to your paper watchlist.</p><button className="text-button" onClick={()=>setManual(true)} disabled={!state}><Plus size={15}/>Add a pair by market ID</button></div>}
 {!!watched.length&&<button className="text-button add-pair" onClick={()=>setManual(true)}><Plus size={15}/>Add a pair by market ID</button>}
 {suggestions.length>0&&<div className="candidate-section"><div className="section-label">MATCH CANDIDATES <span>Text similarity only · rules unverified</span></div>{suggestions.map(x=><div className="candidate" key={x.id}><div><b>{x.a.title}</b><small>{x.b.title}</small></div><button className="secondary" disabled={loading} onClick={()=>view(x.a.id,x.b.id)}>Review<ArrowUpRight size={15}/></button></div>)}</div>}
 {discovery&&suggestions.length===0&&<p className="fine-print">No additional text matches found in this bounded discovery sample. Search the market inventory below or add exact IDs. This does not mean no arbitrage exists across the exchanges.</p>}
 {discovery&&<details className="inventory"><summary>Market inventory · {discovery.kalshi.length+discovery.poly.length} loaded</summary><p className="fine-print">Search above to narrow the list. Select a market ID to copy it into the pair form.</p>{filteredMarkets.map(m=><button className="inventory-row" key={m.venue+m.id} onClick={()=>{if(m.venue==='kalshi')setK(m.id);else setP(m.id);setManual(true);}}><span className={'venue '+m.venue}>{m.venue==='kalshi'?'K':'P'}</span><span><b>{m.title}</b><small>{m.id}</small></span><Plus size={14}/></button>)}</details>}
 </section><aside><section className="panel strategy"><ShieldCheck className="accent" size={25}/><h2>Small bankroll. Strict filters.</h2><div className="cost-lines"><div><span>Maximum per pair</span><b>{money(state?.settings.maxTrade||100000)}</b></div><div><span>Total commitment limit</span><b>{money(state?.settings.maxCommitted||400000)}</b></div><div><span>Minimum net return</span><b>{state?.settings.minRoi||1}%</b></div><div><span>Execution reserve</span><b>{((state?.settings.reserve||200)/100).toFixed(0)}¢ / pair</b></div><div><span>Settlement horizon</span><b>{state?.settings.maxDays||30} days</b></div></div><div className="notice">OHIO RESEARCH PROFILE<br/>Sports excluded. Eligibility for real trading remains unverified. This tool places no real orders.</div><p className="fine-print">The paper bot runs one cycle every 30 seconds while this page is open. Each cycle can simulate at most one entry. REST snapshots cannot establish actual fill probability.</p></section><section className="small-note"><h3>Zero trades is a valid result.</h3><p>Protecting the $100 comes before chasing the target. The bot never raises limits to catch up.</p></section></aside></div>
 <Sheet open={!!inspect||manual} onOpenChange={v=>{if(!v){setInspect(null);setManual(false);}}}><SheetContent className="review-sheet"><SheetTitle>{inspect?'Review the two contracts':'Add a market pair'}</SheetTitle><SheetDescription>{inspect?'Confirm the payoff relationship before paper simulation. This review does not certify legal eligibility.':'Use a Kalshi market ticker and a Polymarket US market slug. Public data only; no API keys.'}</SheetDescription>
 {!inspect?<><label className="field">Kalshi ticker<input value={k} onChange={e=>setK(e.target.value)} placeholder="KX…"/></label><label className="field">Polymarket US slug<input value={p} onChange={e=>setP(e.target.value)} placeholder="Market slug from polymarket.us"/></label><button className="primary" disabled={loading||!k||!p} onClick={()=>view(k.trim(),p.trim())}>{loading?'Loading contracts…':'Load both contracts'}</button></>:<>
 <div className="rules-grid">{[inspect.a,inspect.b].map(m=><article className="rules-card" key={m.venue}><span className={'venue '+m.venue}>{m.venue==='kalshi'?'K':'P'}</span><h3>{m.title}</h3><div className="outcome-label">YES / LONG: {m.outcome}<br/>NO / SHORT: {m.opposite}</div><p className="table-meta">{m.category} · {new Date(m.closeAt).toLocaleDateString()}<br/>Fee coefficient: {m.feeRate===null?'Unknown':(m.feeRate/10000).toFixed(4)}</p><p className="rules-text">{m.rules||'Rules unavailable — pair cannot be approved.'}</p><a href={m.url} target="_blank" rel="noreferrer">Exchange contract<ExternalLink size={13}/></a></article>)}</div>
 <label className="switch-label"><Switch checked={inverted} onCheckedChange={setInverted}/>The long outcomes are opposites</label><p className="fine-print">{inverted?'Hedge with YES + YES or NO + NO.':'Hedge with Kalshi YES + Polymarket US NO, or the reverse.'} Check the named outcomes above.</p>
 {['Same underlying event, threshold, deadline, time zone, and resolution source.','The selected hedge pays a combined $1 per paired contract in every applicable outcome.','Cancellation, ties, postponements, voids, and corrections preserve that payoff.'].map((text,i)=><label className="check-label" key={text}><Checkbox checked={checks[i]} onCheckedChange={v=>setChecks(checks.map((x,j)=>j===i?v===true:x))}/>{text}</label>)}
 <label className="field">Review notes<input value={notes} onChange={e=>setNotes(e.target.value)} maxLength={1000} placeholder="Evidence, shared source, or exception handling"/></label><button className="primary" onClick={approve} disabled={!checks.every(Boolean)||loading}><Check size={16}/>{loading?'Saving…':'Save paper watchlist pair'}</button></>}
 </SheetContent></Sheet></>;
}
