import {readFileSync,writeFileSync} from 'node:fs';import {resolve} from 'node:path';
const [dir,jsonPath,mdPath]=process.argv.slice(2);if(!mdPath)throw Error('Usage: confirmation-report.mjs DIR JSON MD');
const load=n=>JSON.parse(readFileSync(resolve(dir,n),'utf8'));
const s=load('summary.json'),f=load('frozen.json'),status=load('status.json'),coverage=load('coverage.json');
const compact=q=>q?{pairId:q.pairId,category:q.category,at:q.at,aSide:q.aSide,bSide:q.bSide,quantity:q.quantity,positiveExchangeNet:q.positiveExchangeNet,economics:q.economics,pricingReasons:q.pricingReasons,additionalPolicyAdmission:q.additionalPolicyAdmission,tradingAuthorization:q.tradingAuthorization,dataValidity:q.dataValidity,settlementEquivalence:q.settlementEquivalence,fillClaim:false}:null;
const intervals=[...s.completedIntervals,...s.activeIntervals].map(i=>({id:i.id,key:i.key,openedAt:i.openedAt,lastObservedAt:i.lastObservedAt,closedAt:i.closedAt??null,closeReason:i.closeReason??'RUNNING',quantity:i.quantity,detected:compact(i.original),
 confirmations:s.confirmations.filter(c=>c.intervalId===i.id).map(c=>({status:c.status,edgeSurvived:c.edgeSurvived,reasons:c.reasons,window:c.window,startedAt:c.startedAt,endedAt:c.endedAt,repriced:compact(c.repriced),requestEvidence:c.requestEvidence,
  kalshiSnapshot:c.kalshiSnapshot?{sequence:c.kalshiSnapshot.book.sequence,exchangeAt:c.kalshiSnapshot.book.exchangeAt,receivedAt:c.kalshiSnapshot.book.receivedAt,receivedMono:c.kalshiSnapshot.book.receivedMono,processedAt:c.kalshiSnapshot.processedAt}:null,
  contractReview:c.contractReview,fillClaim:false}))}));
const done=s.phase==='STOPPED'&&status.phase==='STOPPED'&&status.exitCode===0&&s.durationMs>=f.policy.durationMs-1000;
const reviews=f.selection.filter(x=>x.contractReview.reviewCompleted).map(x=>x.contractReview);
const report={version:1,status:done?'COMPLETED_BOUNDED_CONFIRMATION':s.phase==='RUNNING'?'RUNNING_PENDING':'STOPPED_INCOMPLETE',startedAt:s.startedAt,observedThrough:s.endedAt??s.startedAt+s.durationMs,deadlineAt:status.deadlineAt,policy:f.policy,coverage,
 metrics:{evaluations:s.evaluations,coalescedUpdates:s.coalesced,distinctCandidateIntervals:s.intervalCount,attempts:s.attempts,confirmationCounts:s.confirmationCounts,seenBooks:s.seenBooks,expectedBooks:s.expectedBooks,missingBooks:s.missingBooks,feedFailures:s.failures,clockFault:s.clockFault,intervalLimitReached:s.intervalLimitReached},
 intervals,bestDisplayed:s.bestDisplayed.map(compact),latestClassification:s.latestClassification.map(compact),contractReviews:reviews,
 baseline:'September 21 baseline preserved; 2.63% was strict freshness pass rate, not feed uptime.',ordersEnabled:false,realFills:0,realizedProfit:'NOT_MEASURED',
 limitations:['Observations and snapshot confirmations are not atomic execution or fills.','Unknown account classification/fragmentation: conservative fee assumptions, not exact billing.','Only the named AOC pair received bounded clause review; other matches are not proven equivalent.','Positive interval duration is observation time, not continuous guaranteed tradability.']};
writeFileSync(jsonPath,JSON.stringify(report,null,2)+'\n');
const usd=x=>x===undefined?'—':(x/10000).toFixed(4),iso=x=>new Date(x).toISOString(),lines=['# Candidate confirmation — '+report.status,'',`Started ${iso(s.startedAt)}; observed through ${iso(report.observedThrough)}; scheduled deadline ${iso(status.deadlineAt)}.`,
'',`Routes ${coverage.selected}; books ${s.seenBooks}/${s.expectedBooks}; distinct positive candidate intervals ${s.intervalCount}; confirmation attempts ${s.attempts}; results ${JSON.stringify(s.confirmationCounts)}. Feed failures ${JSON.stringify(s.failures)}.`,
'','Economic positivity, data validity, settlement equivalence, policy admission and authorization are independent fields. Orders remain disabled. Repeated updates are not new opportunities.',
'','| Interval / pair / side | First detected UTC | Qty | Initial fee-bound surplus | Confirmation | Latest fee-bound surplus | Risk charge | Recovery K / PM | Policy blockers | Contract review |',
'|---|---|---:|---:|---|---:|---:|---|---|---|'];
for(const i of intervals){const c=i.confirmations.at(-1),r=c?.repriced??i.detected,e=r?.economics,review=f.selection.find(x=>x.pair.id===i.detected.pairId)?.contractReview;
 lines.push(`| ${i.id}: ${i.detected.pairId.replaceAll('|','/')} / ${i.detected.aSide}+${i.detected.bSide} | ${iso(i.openedAt)} | ${i.quantity} | ${usd(i.detected.economics?.feeBoundSurplus)} | ${c?.status??'NOT_ATTEMPTED'}${c?.reasons?.length?': '+c.reasons.join(', '):''} (${i.confirmations.length} checks) | ${c?.repriced?usd(e?.feeBoundSurplus):'unconfirmed'} | ${usd(e?.riskAllowance)} | ${usd(e?.recoveryCash?.kalshi)} / ${usd(e?.recoveryCash?.poly)} | ${r?.additionalPolicyAdmission?.blockers.join(', ')??'unknown'} | ${review?.status??'UNRESOLVED'}${review?.reviewCompleted?' (clause review complete)':' (not reviewed)'} |`);
}
if(!intervals.length)lines.push('| No positive valid-discovery interval detected | — | — | — | — | — | — | — | See classified rows and missing-data evidence in JSON | Review remains independent |');
lines.push('','A FAILED check has unknown survival, not zero profit. A surviving fee-bound edge still needs separate settlement review and policy admission; no row authorizes trading or establishes a fill. Original and repriced quantities, prices, receipt/processing/snapshot times, request hashes and cache headers are in the sanitized JSON. Full raw responses stay local.',
'','AOC review: '+(reviews[0]?.status??'UNRESOLVED')+'. See [clause comparison](aoc-contract-review-20260921.json) and [method](CANDIDATE-CONFIRMATION.md). Deadline/timezone and issuance/source precedence are unresolved; exceptional payouts are not proven complementary. Other contracts were not reviewed in this bounded checkpoint.',
'',report.status==='RUNNING_PENDING'?'Collection is still running. This is an interim result, not a completed 30-minute outcome.':'The existing run is stopped. No restart or retuning was performed.');
writeFileSync(mdPath,lines.join('\n')+'\n');console.log(JSON.stringify({status:report.status,intervals:intervals.length,confirmations:s.confirmationCounts}));
