// Derive publication-safe route summaries; never copy HTTP bodies, credentials,
// raw books, account data or databases into the outgoing report.
import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {resolve} from 'node:path';
const [input,jsonOut,mdOut]=process.argv.slice(2);
if(!input||!jsonOut||!mdOut)throw Error('Usage: discovery-report.mjs RUN_DIR SUMMARY_JSON REPORT_MD');
const read=(name)=>JSON.parse(readFileSync(resolve(input,name),'utf8'));
const frozen=read('frozen.json'),coverage=read('coverage.json'),run=read('summary.json');
const entries=new Map(frozen.selection.map(e=>[e.pair.id,e]));
const batches=run.batches.map(b=>({...b,summary:read(b.path+'/summary.json')}));
const categoryByPair=new Map(batches.flatMap(b=>b.summary.routeObservation.map(o=>[o.pairId,o.category])));
const reviews=existsSync(resolve(input,'triage.json'))?read('triage.json'):[];
const compact=q=>q?{pairId:q.pairId,at:q.at,aSide:q.aSide,bSide:q.bSide,quantity:q.quantity,positiveExchangeNet:q.positiveExchangeNet,
 marketStatus:q.marketStatus?{kalshi:{classification:q.marketStatus.kalshi.classification,reasons:q.marketStatus.kalshi.reasons},poly:q.marketStatus.poly}:null,pricingReasons:q.pricingReasons,quantitySelection:q.quantitySelection,additionalPolicyAdmission:q.additionalPolicyAdmission,
 economics:q.economics?{cost:q.economics.cost,feeBound:q.economics.feeBound,feeBoundSurplus:q.economics.feeBoundSurplus,
  kalshi:{cost:q.economics.kalshi.cost,feeBound:q.economics.kalshi.feeBound,levels:q.economics.kalshi.levels},poly:{cost:q.economics.poly.cost,feeBound:q.economics.poly.feeBound,levels:q.economics.poly.levels},
  riskAllowance:q.economics.riskAllowance,afterRisk:q.economics.afterRisk,recoveryCash:q.economics.recoveryCash,reservedCash:q.economics.reservedCash,venueReservedCash:q.economics.venueReservedCash,simulatedCapital:q.economics.simulatedCapital,feeProvenance:q.economics.feeProvenance,feeUncertainty:q.economics.feeUncertainty}:null,
 timestamps:q.dataValidity?{kalshi:q.dataValidity.kalshi.timestamps,poly:q.dataValidity.poly.timestamps}:null}:null;
const stamp=r=>r?{receivedAt:r.e.book.receivedAt,exchangeAt:r.e.book.exchangeAt,processedAt:r.e.processedAt,version:r.e.version,sequence:r.e.book.sequence,transactTime:r.transactTime??null}:null;
const confirmations=batches.flatMap(b=>b.summary.confirmations.map(c=>({batch:b.index,status:c.status,edgeSurvived:c.edgeSurvived,reasons:c.reasons,intervalId:c.intervalId,
 original:compact(c.original),repriced:compact(c.repriced),window:c.window??{startedAt:c.startedAt,endedAt:c.endedAt},
 bookConfirmation:{accepted:c.bookConfirmation?.accepted??false,reasons:c.bookConfirmation?.reasons??c.reasons,
  kalshi:stamp(c.bookConfirmation?.kalshi?.selected??c.bookConfirmation?.kalshi?.response),poly:stamp(c.bookConfirmation?.poly?.selected??c.bookConfirmation?.poly?.response)},
 marketStatus:{kalshi:{classification:c.marketStatus?.kalshi?.classification??'UNRESOLVED',reasons:c.marketStatus?.kalshi?.reasons??[]},poly:c.marketStatus?.poly??null},tradingAuthorized:false,fillClaim:false})));
const distinct=new Map();
const add=(q,batch,result=null)=>{if(!q?.economics)return;const key=q.pairId+'|'+q.aSide,e=entries.get(q.pairId),old=distinct.get(key),confirmed=result?.status==='EDGE_SURVIVED';
 const row={key,batch,category:categoryByPair.get(q.pairId)??e.pair.a.category,kalshiId:e.pair.a.id,polyId:e.pair.b.id,title:e.pair.a.title,referenceCase:e.contractReview.referenceCase===true,quote:compact(q),confirmation:result,
  marketStatus:result?.marketStatus??(q.marketStatus?{kalshi:{classification:q.marketStatus.kalshi.classification,reasons:q.marketStatus.kalshi.reasons},poly:q.marketStatus.poly}:null),
  statusAtBatchEnd:(()=>{const s=batches.find(b=>b.index===batch)?.summary.marketStatus?.[e.pair.a.id];return s?{classification:s.classification,reasons:s.reasons,reportedStatus:s.reportedStatus}:null;})(),
  settlement:reviews.find(r=>r.pairId===q.pairId)??{status:'UNRESOLVED',reason:e.contractReview.reason},
  smallCapitalFeasible:q.economics.venueReservedCash?.kalshi<=frozen.policy.simulatedCapital.kalshi&&q.economics.venueReservedCash?.poly<=frozen.policy.simulatedCapital.poly,
  liquidityGroup:[e.pair.a.id,e.pair.b.id],tradingAuthorized:false,fillClaim:false};
 if(!old||Number(confirmed)>Number(old.confirmation?.status==='EDGE_SURVIVED')||confirmed===(old.confirmation?.status==='EDGE_SURVIVED')&&q.economics.feeBoundSurplus>old.quote.economics.feeBoundSurplus)distinct.set(key,row);
};
for(const b of batches)for(const q of b.summary.bestUsable??[])add(q,b.index);
for(const c of confirmations)if(c.status==='EDGE_SURVIVED')add(c.repriced,c.batch,c);
// Unconfirmed rows retain their exact displayed timestamp; a different request
// is recorded separately and cannot confer confirmation on that observation.
for(const row of distinct.values())if(!row.confirmation)row.otherConfirmationAttempts=confirmations.filter(c=>c.original?.pairId===row.quote.pairId&&c.original?.aSide===row.quote.aSide).map(c=>({status:c.status,reasons:c.reasons,quantity:c.original.quantity,at:c.original.at,confirmedAt:c.repriced?.at??null}));
const ranked=[...distinct.values()].sort((a,b)=>Number(b.confirmation?.status==='EDGE_SURVIVED')-Number(a.confirmation?.status==='EDGE_SURVIVED')||b.quote.economics.feeBoundSurplus-a.quote.economics.feeBoundSurplus);
const observations=batches.flatMap(b=>b.summary.routeObservation.map(r=>({...r,batch:b.index,observationStartedAt:b.startedAt,observationEndedAt:b.endedAt,observationWindowMs:b.durationMs,pricingReasonsAtLastObservation:Object.fromEntries((b.summary.latestClassification??[]).filter(q=>q.pairId===r.pairId).map(q=>[q.aSide+'+'+q.bSide,q.pricingReasons]))})));
const attempted=new Set(observations.map(o=>o.pairId)),omitted=[...coverage.omitted,...frozen.selection.filter(e=>!attempted.has(e.pair.id)).map(e=>({pairId:e.pair.id,kalshiId:e.pair.a.id,polyId:e.pair.b.id,reason:'BATCH_NOT_REACHED_'+run.reason}))];
const confirmedSmallWins=confirmations.filter(c=>c.status==='EDGE_SURVIVED'&&c.original?.quantity<10&&c.original.quantitySelection?.compared.some(q=>q.quantity>c.original.quantity&&q.feeBoundSurplus!==null&&q.feeBoundSurplus<=0)).map(c=>({pairId:c.original.pairId,aSide:c.original.aSide,bSide:c.original.bSide,at:c.original.at,quantity:c.original.quantity,selectedSurplus:c.original.economics.feeBoundSurplus,maximum:c.original.quantitySelection.compared.filter(q=>q.feeBoundSurplus!==null).at(-1),confirmedAt:c.repriced?.at,confirmedSurplus:c.repriced?.economics?.feeBoundSurplus}));
const perCategory=new Map();const retained=ranked.filter(row=>{if(row.referenceCase||row.confirmation?.status==='EDGE_SURVIVED')return true;const bucket=row.category+'|'+(row.quote.positiveExchangeNet?'UNCONFIRMED_POSITIVE':'NEAREST_MISS'),n=perCategory.get(bucket)??0;perCategory.set(bucket,n+1);return n<3;});
const counts={matched:coverage.matched,planned:coverage.selected,attempted:attempted.size,subscribed:observations.filter(o=>o.bothBooksAt!==null).length,subscriptionRequested:observations.filter(o=>o.subscriptionRequestedAt!==null).length,bothBooksReceived:observations.filter(o=>o.bothBooksAt!==null).length,usable:observations.filter(o=>o.firstUsableAt!==null).length,priced:observations.filter(o=>o.economicEvaluations>0).length,omitted:omitted.length,omittedCount:omitted.length,
 distinctValidComparisons:ranked.length,validPositiveComparisons:ranked.filter(r=>r.quote.positiveExchangeNet).length,unconfirmedPositiveComparisons:ranked.filter(r=>r.quote.positiveExchangeNet&&r.confirmation?.status!=='EDGE_SURVIVED').length,validNonpositiveComparisons:ranked.filter(r=>!r.quote.positiveExchangeNet).length,confirmedPositiveNew:ranked.filter(r=>!r.referenceCase&&r.confirmation?.status==='EDGE_SURVIVED').length,confirmedPositiveReference:ranked.filter(r=>r.referenceCase&&r.confirmation?.status==='EDGE_SURVIVED').length};
const usableTimes=observations.map(o=>o.usableMs??0).sort((a,b)=>a-b);
const report={scope:'ORDER_DISABLED_DEPTH_AWARE_DISCOVERY',startedAt:run.startedAt,endedAt:run.endedAt,actualWindowMs:run.endedAt-run.startedAt,usableTimeMs:{min:usableTimes[0]??null,median:usableTimes[Math.floor(usableTimes.length/2)]??null,max:usableTimes.at(-1)??null},reason:run.reason,policy:frozen.policy,sourceManifest:frozen.manifest,
 coverage:{...counts,catalogComplete:coverage.catalogComplete,catalogErrors:coverage.catalogErrors,listing:coverage.listing,matchingDiagnostics:coverage.matchingDiagnostics,categories:coverage.categories,omitted,observations,
  definitions:{attempted:'Route assigned to a started batch.',subscribed:'Both venue feeds delivered an initial book; this is stronger than a sent subscription request but is not a validity or status claim.',subscriptionRequested:'Both venue subscription messages sent; not an acknowledgement.',bothBooksReceived:'Both subscribed feeds delivered at least one book; not necessarily valid.',usable:'At least one evaluation passed both discovery validity gates. Quiet reconstruction still requires requested-book confirmation.',usableMs:'Time between sampled validity states with a maximum 1-second measurement gap, excluding bootstrap and unsampled stalls. Not all-universe simultaneous coverage.'}},
 batches:batches.map(({summary,routeObservation,...b})=>({...b,bothBooksReceived:routeObservation.filter(r=>r.bothBooksAt!==null).length,usable:routeObservation.filter(r=>r.firstUsableAt!==null).length})),confirmationCounts:Object.fromEntries(['EDGE_SURVIVED','EDGE_DISAPPEARED','FAILED'].map(k=>[k,confirmations.filter(c=>c.status===k).length])),confirmations,ranked:retained,rankingSelection:{distinctComparisons:ranked.length,retained:retained.length,rule:'All confirmed-positive and reference routes; up to three unconfirmed-positive and three nearest-miss rows per category. Full derived comparisons remain in local evidence.'},quantityCorrectionEvidence:confirmedSmallWins,triage:reviews,
 capital:'$50 simulated per venue; whole quantities 1–10 only. No larger-size scenarios evaluated. Recovery cash is reserved capital, not an expense; risk allowance is separate from fees.',
 note:'No fills, orders, ledger changes, realized profit, settlement equivalence or live authorization inferred. Repeated confirmations, overlapping sizes and shared liquidity are not additive profits. Nothing is inferred about unobserved times or unavailable feeds.'};
const compactArrays=new Set(['observations','confirmations','ranked','batches','triage','quantityCorrectionEvidence']);
function publicationJSON(value,name='',depth=0){
 if(value===null||typeof value!=='object')return JSON.stringify(value);
 const pad='  '.repeat(depth),next=pad+'  ';
 if(Array.isArray(value))return compactArrays.has(name)&&value.length?'[\n'+value.map(x=>next+JSON.stringify(x)).join(',\n')+'\n'+pad+']':JSON.stringify(value);
 return '{\n'+Object.entries(value).filter(([,v])=>v!==undefined).map(([k,v])=>next+JSON.stringify(k)+': '+publicationJSON(v,k,depth+1)).join(',\n')+'\n'+pad+'}';
}
writeFileSync(jsonOut,publicationJSON(report)+'\n');
const iso=t=>t===null||t===undefined?'—':new Date(t).toISOString(),usd=n=>n===null||n===undefined?'—':(n<0?'-':'')+'$'+(Math.abs(n)/10000).toFixed(4),esc=s=>String(s).replaceAll('|','/');
const lines=['# Depth-aware discovery checkpoint','',`${iso(run.startedAt)}–${iso(run.endedAt)}; ${(report.actualWindowMs/60000).toFixed(2)} minutes. ${run.reason}. Orders disabled.`,
 '',`${counts.matched} matched / ${counts.planned} planned / ${counts.attempted} attempted / ${counts.subscriptionRequested} subscription-requested / ${counts.subscribed} subscribed (both books received) / ${counts.usable} usable / ${counts.omitted} omitted. ${batches.length} sequential batches; no simultaneous-universe coverage or claim about unobserved periods.`,
 '',`Per-route sampled usable time: ${((report.usableTimeMs.min??0)/1000).toFixed(3)}–${((report.usableTimeMs.max??0)/1000).toFixed(3)} seconds, median ${((report.usableTimeMs.median??0)/1000).toFixed(3)}. ${counts.priced} routes produced a priced direction; ${counts.attempted-counts.priced} produced no supported quote. ${counts.validPositiveComparisons} distinct valid positive comparisons, ${counts.unconfirmedPositiveComparisons} unconfirmed; ${counts.validNonpositiveComparisons} nonpositive. Unsupported quotes and missing data are not negative economics.`, '',report.capital,'',`Confirmations: ${JSON.stringify(report.confirmationCounts)}. New distinct confirmed-positive routes: ${counts.confirmedPositiveNew}; reference routes: ${counts.confirmedPositiveReference}.`,
 '', 'Ranked distinct new routes (one representative per venue pair and side; never summed). Fee-net arithmetic assumes complementary $1 payouts. The three reviewed mismatches invalidate that assumption; the other routes remain unreviewed:','',
 '| Venue IDs / sides | UTC quote / confirmation | Qty | Entry K / PM | Fee bound K / PM | Fee-net surplus | Confirmation | Separate risk / recovery K / PM | Blockers |',
 '|---|---|---:|---|---|---|---|---|---|'];
for(const row of ranked.filter(r=>!r.referenceCase).slice(0,10)){const q=row.quote,e=q.economics,c=row.confirmation;
 lines.push(`| ${esc(row.kalshiId)} ${q.aSide} / ${esc(row.polyId)} ${q.bSide} | ${iso(q.at)} / ${iso(c?.window?.endedAt)} | ${q.quantity} | ${usd(e.kalshi.cost)} / ${usd(e.poly.cost)} | ${usd(e.kalshi.feeBound)} / ${usd(e.poly.feeBound)} | ${usd(e.feeBoundSurplus)} | ${c?.status??'NOT_CONFIRMED_AT_THIS_QUOTE'} | ${usd(e.riskAllowance)} / ${usd(e.recoveryCash.kalshi)} / ${usd(e.recoveryCash.poly)} | ${esc([...(q.additionalPolicyAdmission?.blockers??[]),row.marketStatus?.kalshi?.classification??'STATUS_UNRESOLVED',row.settlement.status,'ORDER_DISABLED'].join(', '))} |`);
}
lines.push('','| Batch | UTC start–end | Routes | Both books / usable | Confirmation attempts | Feed failures |','|---|---|---:|---|---:|---|');
for(const b of batches)lines.push(`| ${b.index+1} | ${iso(b.startedAt)}–${iso(b.endedAt)} | ${b.routes} | ${b.routeObservation.filter(r=>r.bothBooksAt!==null).length} / ${b.routeObservation.filter(r=>r.firstUsableAt!==null).length} | ${b.attempts} | ${esc(JSON.stringify(b.failures))} |`);
lines.push('',report.note,'','Per-route usable time, missing-data reasons, all confirmed-positive comparisons, selected nearest misses, exact confirmation receipts and omissions are in [the sanitized summary](summary.json). Primary-term triage is in [TRIAGE.md](TRIAGE.md). Historical PR #7 evidence is unchanged.');
lines.push('',`Quantity correction: ${confirmedSmallWins.length} confirmed routes had a smaller positive quantity while the maximum supported quantity was nonpositive at detection. These are alternatives within a route, not additive trades. See quantityCorrectionEvidence in the summary.`, '', 'Next research action: add narrow matcher exclusions/regressions for the reviewed Spotify geography and Israeli office-role mismatches before another authorized discovery window. No further work or collection is authorized by this report.');
lines.push('', 'Smaller-quantity examples (maximum evaluated at detection; only the selected quantity was confirmed; primary terms unreviewed):', '', '| Venue IDs / sides | Detection / confirmation UTC | Qty | Entry cost / fee bound | Confirmed fee-net | Maximum quantity fee-net at detection |', '|---|---|---:|---|---|---|');
for(const x of [...confirmedSmallWins].sort((a,b)=>b.confirmedSurplus-a.confirmedSurplus).slice(0,3)){const c=confirmations.find(c=>c.original?.pairId===x.pairId&&c.original.at===x.at),q=c.repriced;lines.push(`| ${esc(x.pairId)} / ${x.aSide}+${x.bSide} | ${iso(x.at)} / ${iso(x.confirmedAt)} | ${x.quantity} | ${usd(q.economics.cost)} / ${usd(q.economics.feeBound)} | ${usd(x.confirmedSurplus)} | q=${x.maximum.quantity}: ${usd(x.maximum.feeBoundSurplus)} |`);}
writeFileSync(mdOut,lines.join('\n')+'\n');
console.log(JSON.stringify({counts,confirmationCounts:report.confirmationCounts,actualWindowMs:report.actualWindowMs,newTop:ranked.filter(r=>!r.referenceCase).slice(0,3).map(r=>({key:r.key,net:r.quote.economics.feeBoundSurplus,confirmation:r.confirmation?.status??'NOT_CONFIRMED_AT_THIS_QUOTE'}))}));
